src/fastmcp/resources/manager.py
src/fastmcp/server.py
tests/test_server.py

Prepare to list templates

---

examples/desktop.py
examples/echo.py
examples/screenshot.py
examples/simple_echo.py
src/fastmcp/cli/claude.py
src/fastmcp/cli/cli.py

Ensures that `fastmcp run`, `fastmcp dev`, and `fastmcp install` all accept `path/to/server.py` and `path/to/server.py:my_app`

Update cli file spec

---

src/fastmcp/server.py

This log causes errors in the dev server for some reason

Remove log

---

README.md

Accidentally left in place in #27

Remove top level env var

---

README.md

add `Contributing` section to README

---

src/fastmcp/cli/claude.py

Handle missing config file when installing

---

src/fastmcp/resources/base.py

Remove BaseURL reference and use AnyURL

---

pyproject.toml

-Updating License in `pyproject.toml` due to #54

patch: Update pyproject.toml license

---

src/fastmcp/server.py

what it says on the tin. Plus addition of py.typed

Decorator typing

---

pyproject.toml
src/fastmcp/clients/base.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
tests/clients/test_fastmcp_client.py
tests/prompts/test_prompt_manager.py
tests/resources/test_resource_manager.py
tests/server/test_proxy.py
tests/tools/test_tool_manager.py
uv.lock

```python
client = # any FastMCPClient connected to an existing server
proxy = FastMCP.as_proxy(client)
```

Add MCP proxy server

---

src/fastmcp/server/server.py
tests/server/test_server.py

The tool conversion logic assumed that a list of items corresponded to a list of MCP types, so if a tool returned a "regular" list, like `[1, 2]` it was turned into e.g. `[TextContent(content='1'), TextContent(content='2')]`. This fixes the behavior to group any "non-MCP" values into a single Content object, while still respecting the possibility that users will return a mix of Python and MCP types.

Fix bug with tools that return lists

---

src/fastmcp/client/client.py
src/fastmcp/server/proxy.py
tests/client/test_client.py
tests/client/test_roots.py
tests/client/test_sampling.py

The Client class changes focus on API simplification and improved error handling:
1. **Unwrapped return values**: Methods now return direct results instead of wrapper objects
- `list_resources()` returns `list[Resource]` instead of `ListResourcesResult`
- `list_tools()` returns `list[Tool]` instead of `ListToolsResult` 
- Similar pattern for other methods like `read_resource()`, `list_prompts()`, etc.
2. **Enhanced error handling**:
- Added `ClientError` class as base exception type
- `call_tool()` now raises `ClientError` with meaningful messages on failure
3. **Improved type safety**:
- Added `@overload` annotations for `call_tool()` method
- Better typing with `Literal` types for the raw result parameter
4. **New parameter options**:
- Added `_return_raw_result` parameter to …

Improve client return types

---

src/fastmcp/server/server.py
tests/server/test_mount.py

Ensures that mounted app (i.e. sub-MCPs) lifespans are properly entered and exited. Closes #127

Enter mounted app lifespans

---

examples/smart_home/src/smart_home/hub.py
examples/smart_home/src/smart_home/lights/server.py

i forgot to update this before I merged #115

fix branch name in example

---

docs/docs.json
docs/patterns/decorating-methods.mdx
src/fastmcp/exceptions.py
src/fastmcp/prompts/__init__.py
src/fastmcp/prompts/prompt.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/__init__.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/server/context.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/decorators.py
src/fastmcp/utilities/func_metadata.py
tests/prompts/test_base.py
tests/prompts/test_prompt_manager.py
tests/resources/test_resource_manager.py
tests/server/test_file_server.py
tests/server/test_openapi.py
tests/server/test_proxy.py
tests/server/test_server.py
tests/utilities/test_decorated_function.py

This PR closes #55, primarily by documenting a working approach but secondarily by adding comprehensive tests and support for decorated methods. 
Note that decorating an instance or class method as a tool is not going to work as the MCP-bound tool will never recover its missing instance or class bind. 
* [`docs/docs.json`](diffhunk://#diff-873ce17c654718debe2fe308a2f2279bde8663686423c51f97fab2dd0722b8d9L58-R62): Updated the "Advanced Patterns" group to "Patterns" and added a new page for decorating methods.
* [`docs/patterns/decorating-methods.mdx`](diffhunk://#diff-c80316fd83f62b14270a68779122125e70414c2ae327b033d4b82cfef5c7c6dbR1-R198): Added a comprehensive guide on properly using instance methods, class methods, and static methods with FastMCP decorators.
* …

Expand support for various method interactions

---

docs/patterns/openapi.mdx
src/fastmcp/utilities/openapi.py
tests/utilities/openapi/test_openapi.py

Support openapi 3.0 and 3.1

---

docs/servers/resources.mdx
src/fastmcp/resources/resource_manager.py
src/fastmcp/resources/template.py
src/fastmcp/server/server.py
tests/resources/test_resource_template.py
tests/server/test_server.py

Allow resource templates to have optional / excluded arguments

---

src/fastmcp/prompts/prompt.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/template.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
tests/resources/test_resource_template.py
tests/server/test_mount.py

This pull request introduces several enhancements and refactors to the `fastmcp` package, focusing on prompt management, resource handling, and proxy functionality. The most important changes include adding methods to convert prompts to MCP format, updating prompt and tool management to use keys instead of names, and ensuring proper handling of URI parameters.
* Added `to_mcp_prompt` method in `Prompt` to convert prompts to MCP format (`src/fastmcp/prompts/prompt.py`).
* Introduced methods in `PromptManager` to list MCP prompts and refactored prompt retrieval to use keys (`src/fastmcp/prompts/prompt_manager.py`). [[1]](diffhunk://#diff-39627f28d8caefc4636d1b2b8b4f42d5f81198a2a63721528195fadd60a4d940L33-R48) [[2]](diffhunk://#diff-39627f28d8caefc4636d1b2b8b4f42d5f81198a2a63721528195fadd60a4 …

Create MCP prompts on object; fix issue with forwarding proxy templates

---

src/fastmcp/client/transports.py

Add npx validation

---

tests/client/test_client.py

Remove mock transport

---

docs/clients/client.mdx

Document ping

---

README.md
docs/servers/tools.mdx
src/fastmcp/tools/tool.py
tests/tools/test_tool_manager.py

Indicate that Image class is for returns

---

src/fastmcp/cli/cli.py

Allows customization of the MCP Inspector's:
- UI port
- Proxy port
- Version
when running `fastmcp dev`

Allow customization of inspector proxy port, ui port, and version

---

docs/servers/resources.mdx
src/fastmcp/resources/template.py
tests/resources/test_resource_template.py
tests/server/test_server.py

Wildcard matching was added in #246 but an error was raised if used in a decorator

Ensure servers expose template wildcards

---

docs/patterns/fastapi.mdx
docs/patterns/openapi.mdx
src/fastmcp/server/openapi.py
tests/server/test_openapi.py

Expose configurable timeout for OpenAPI

---

docs/patterns/fastapi.mdx
docs/patterns/openapi.mdx

Fix OpenAPI examples

---

docs/clients/client.mdx
src/fastmcp/client/client.py
src/fastmcp/client/logging.py
src/fastmcp/client/sampling.py
src/fastmcp/server/context.py
tests/client/test_logs.py
tests/server/test_server_interactions.py

Fix client docs for advanced features, add tests for logging

---

docs/patterns/openapi.mdx
src/fastmcp/server/openapi.py
tests/server/test_openapi.py

Addresses and possibly closes #271

Improve OpenAPI param handling

---

docs/servers/tools.mdx
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_manager.py
tests/server/test_tool_annotations.py

Add support for tool annotations

---

.github/workflows/run-tests.yml
README.md
docs/servers/fastmcp.mdx
justfile
src/fastmcp/server/server.py
src/fastmcp/settings.py
tests/server/test_auth_integration.py

Inherit from MCP 1.7.1 support
Closes #98

Add auth support

---

src/fastmcp/server/openapi.py
src/fastmcp/server/proxy.py
src/fastmcp/tools/tool.py
tests/tools/test_tool.py
tests/tools/test_tool_manager.py

Following #314, there's no need to track is_async anymore.

Remove is_async attribute

---

src/fastmcp/server/server.py

Add timeout-graceful-shutdown as a default config for SSE app

---

docs/getting-started/quickstart.mdx

Example fails without the import

Update quickstart.mdx example to include import

---

tests/test_examples.py

Upstream changes inadvertently caused a test in #306 to fail

Fix prompt test

---

docs/docs.json
docs/patterns/http-requests.mdx
docs/servers/context.mdx

- `get_context()`
- `get_http_request()`

Add dependency docs for context / http requests

---

src/fastmcp/server/server.py

Closes #352, may relate to a bug reported on Bluesky https://bsky.app/profile/themadtinker.bsky.social/post/3loh2aw3zps2q

Ensure a response is returned from sse endpoint

---

.github/workflows/run-tests.yml
src/fastmcp/server/http.py

Fix import error

---

README.md
docs/getting-started/welcome.mdx

Add llms.txt to docs

---

tests/utilities/test_types.py

Hi again,
Added some tests to Image type to improve code coverage. They pass ok when run.

Adding a few tests to Image type

---

tests/utilities/test_cache.py

Hi, 
Added tests for TimedCache class
Best,
Didier

Adding tests for TimedCache

---

tests/cli/test_cli.py

Hi,
As per title, adding 23 tests to cover the CLI code.
They pass 100% when executed on my fork of fastmcp
Best,
Didier

Adding 23 tests for CLI

---

src/fastmcp/server/server.py
src/fastmcp/utilities/tests.py
tests/client/test_sse.py

Fix bug that sets message path and sse path to same value

---

docs/servers/tools.mdx

cc @davenpi 
Documentation for new feature in #437

Add documentation for tool removal

---

src/fastmcp/prompts/prompt.py
src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/json_schema.py
src/fastmcp/utilities/openapi.py
tests/server/test_openapi.py
tests/utilities/test_json_schema.py
tests/utilities/test_typeadapter.py

Ensure openapi defs for structured objects are loaded properly

---

src/fastmcp/server/server.py

Ensure result is only returned if a new key was found

---

.github/workflows/run-static.yml
.github/workflows/run-tests.yml
tests/client/test_sse.py

Tests are required so if they skip they block merges like in #460

run tests on all PRs

---

docs/servers/proxy.mdx
examples/in_memory_proxy_example.py

closes https://github.com/jlowin/fastmcp/issues/459

update proxy docs + example

---

src/fastmcp/cli/cli.py

closes https://github.com/jlowin/fastmcp/issues/472

add null check

---

pyproject.toml
src/fastmcp/server/http.py
src/fastmcp/server/server.py

we can incrementally strongly type the places that matter the most with the `strict` key in the `pyright` table

strict typing for `server.py`

---

docs/getting-started/quickstart.mdx

- Removing the unused import statement
- Adding the missing import statement

Doc(quickstart): Fix import statements

---

AGENTS.md

- document repo layout and major modules in AGENTS.md
- reiterate the preferred validation commands
- `uv sync`
- `uv run pre-commit run --files AGENTS.md` *(skipped: no files to check)*
- `uv run pytest` *(fails: TestFileResource::test_permission_error)*

Improve AGENTS.md overview

---

docs/clients/transports.mdx
src/fastmcp/client/transports.py
tests/client/test_client.py

Infer sse transport from urls containing /sse

---

docs/clients/client.mdx
docs/clients/transports.mdx
docs/servers/composition.mdx
docs/servers/proxy.mdx
src/fastmcp/server/server.py

2.3.6 was ultimately released as 2.4.0 due to minor breaking changes

Bump 2.3.6 references to 2.4.0

---

src/fastmcp/client/transports.py
src/fastmcp/server/openapi.py
tests/client/test_openapi.py

Use lowercase name for headers when comparing

---

src/fastmcp/client/client.py

add init_timeout for mcp client

---

src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
tests/server/test_proxy.py

Closes #594, ensures proper handling of tools without descriptions

Fix handling tools without descriptions

---

docs/servers/fastmcp.mdx
src/fastmcp/server/server.py
tests/server/test_server.py
uv.lock

Allows tools to be passed as an init kwarg to the FastMCP server

Support providing tools at init

---

src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/server/openapi.py
src/fastmcp/server/proxy.py
src/fastmcp/tools/tool.py
tests/resources/test_resource_template.py

Follow up to #700 / #701 / #702 for templates

Formalize template/functiontemplate split

---

README.md
docs/clients/transports.mdx
docs/deployment/asgi.mdx
docs/deployment/running-server.mdx
docs/getting-started/quickstart.mdx
docs/getting-started/welcome.mdx
docs/integrations/anthropic.mdx
docs/integrations/claude-desktop.mdx
docs/integrations/gemini.mdx
docs/integrations/openai.mdx
docs/patterns/cli.mdx
docs/patterns/decorating-methods.mdx
docs/patterns/http-requests.mdx
docs/patterns/testing.mdx
docs/servers/auth/bearer.mdx
docs/servers/composition.mdx
docs/servers/context.mdx
docs/servers/fastmcp.mdx
docs/servers/prompts.mdx
docs/servers/proxy.mdx
docs/servers/tools.mdx
tests/server/test_server_interactions.py

Reimplements #714 and reverses #715

Remove empty parens from decorators in docs

---

docs/servers/fastmcp.mdx
src/fastmcp/server/server.py

Restore .settings access as deprecated

---

src/fastmcp/server/server.py

Address comment from #803 - handle False correctly

Ensure we handle false http kwargs correctly; removed unused kwarg

---

docs/clients/auth/bearer.mdx

Update headers in docs

---

src/fastmcp/server/server.py

Minor change to follow up #842

Update version to not be positional

---

docs/docs.json
docs/python-sdk/fastmcp-cli-claude.mdx
docs/python-sdk/fastmcp-cli-run.mdx
docs/python-sdk/fastmcp-client-auth-oauth.mdx
docs/python-sdk/fastmcp-server-auth-providers-bearer.mdx
docs/python-sdk/fastmcp-server-server.mdx
docs/python-sdk/fastmcp-tools-tool_transform.mdx
docs/python-sdk/fastmcp-utilities-json_schema.mdx
justfile
src/fastmcp/client/auth/oauth.py

see https://github.com/zzstoatzz/mdxify/releases/tag/v0.2.9

Fix api ref rendering

---

docs/.cursor/rules/mintlify.mdc
docs/clients/logging.mdx
docs/clients/progress.mdx
docs/clients/sampling.mdx
docs/servers/auth/bearer.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/server.mdx
docs/servers/tools.mdx

Uses mintlify components for better presentation of function arguments / object attributes

Clean up parameter documentation

---

examples/mount_example.py

Updates `mount_example.py` to work with the current fastmcp API (v2.9.0). The example was broken due to API changes in recent versions.
The mount example was failing with the following issues:
1. **Deprecation warnings** for `mount()` method calls using old positional argument order
2. **TypeError** when calling `list_tools()` - method became async but wasn't awaited
3. **Incorrect resource URI handling** - prefix format changed from `prefix+` to URL-based structure
```python
DeprecationWarning: Mount prefixes are now optional and the first positional argument should be the server you want to mount.
TypeError: object of type 'coroutine' has no len()
RuntimeWarning: coroutine 'ToolManager.list_tools' was never awaited
```
- __Fixed mount() calls__: Updated to use keyword arguments …

fix(examples): update mount_example.py to work with current fastmcp API

---

CLAUDE.md
docs/servers/middleware.mdx
src/fastmcp/server/middleware/__init__.py
src/fastmcp/server/middleware/middleware.py

Update middleware imports and documentation

---

src/fastmcp/server/server.py
src/fastmcp/utilities/cli.py

Continue refining banner. Adds emojis and uses console.log with stderr=True to avoid confusing local clients like Claude Desktop

Update banner and use console.log

---

src/fastmcp/tools/tool_transform.py
tests/tools/test_tool_transform.py

Fixes https://github.com/jlowin/fastmcp/issues/1065

Keep json schema $defs on transform

---

docs/integrations/fastapi.mdx
docs/integrations/openapi.mdx

Update fastapi docs

---

src/fastmcp/utilities/json_schema.py

fix: preserve def reference when referenced in allOf / oneOf / anyOf

---

docs/servers/tools.mdx

Update docs to reflect sync tools

---

docs/servers/middleware.mdx
src/fastmcp/server/middleware/middleware.py
tests/server/middleware/test_middleware.py

Fix typing, add tests for tool call middleware

---

docs/servers/resources.mdx

Add annotations docs

---

tests/server/middleware/test_middleware.py

Confirms the situation in #1300 was closed in #1282
Closes #1300

Add test for proxy tags visibility

---

src/fastmcp/utilities/openapi.py

OpenAPI parsing performance regression causing excessive processing time for large schemas (e.g., GitHub API).
Performance test failure: parsing time increased from expected <10s to 11.47s, exceeding the established threshold.
Achieved significant performance improvement by optimizing dictionary copy operations in two critical functions that
process OpenAPI schemas during parsing.
🔧 Optimizations Implemented
1. _make_optional_parameter_nullable Function
- Before: Used schema.copy() to create full dictionary copy, then moved properties via del operations
- After: Direct dictionary construction without intermediate copying and deletion
- Enhancement: Replaced list iteration with set lookups for type-specific property classification
2. _adjust_union_types Function
- Before: Always copied …

perf: optimize OpenAPI parsing by reducing dict copy operations

---

docs/servers/resources.mdx

Remove reference to stacked decorators

---

src/fastmcp/utilities/openapi.py

Optimizes string operations in OpenAPI parameter processing by replacing chained `replace()` calls with
`str.translate()` for more efficient character removal.
- **Performance improvement**: Replace chained string operations with single-pass `str.translate()` in
`format_array_parameter()`
- **Location**: `src/fastmcp/utilities/openapi.py`
- **Impact**: 24% performance improvement (1.24x speedup) with 36.84 microseconds saved per operation
```python
str_value = (
str(values)
.replace("[", "")
.replace("]", "")
.replace("'", "")
.replace('"', "")
)
After
translation_table = str.maketrans("", "", "[]'\"")
str_value = str(values).translate(translation_table)
```
Why This Change?
- Performance: str.translate() is a native C-level operation that processes all character replacements in a single …

perf: optimize string operations in OpenAPI parameter processing

---

src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_transform.py
tests/server/test_tool_transformation.py
tests/tools/test_tool.py
tests/tools/test_tool_transform.py

Ensure transformed tools generate structured content

---

.claude/commands/dedupe.md
.github/workflows/auto-close-duplicates.yml
.github/workflows/claude-dedupe-issues.yml
scripts/auto_close_duplicates.py

Using Marvin to dedupe issues, similar to what's done on the Claude Code repo - may take a few tries to get right since we have to test "live"

Add dedupe workflow

---

.github/workflows/marvin.yml

Give Marvin the power of the Internet

---

docs/docs.json
docs/python-sdk/fastmcp-client-auth-oauth.mdx
src/fastmcp/client/auth/oauth.py

Dont know why this is only an issue on some branches

Fix oauth pyright type checking

---

docs/python-sdk/fastmcp-utilities-logging.mdx
src/fastmcp/utilities/logging.py

involve kwargs to pass parameters on creating RichHandler for logging customization.

---

AGENTS.md

Add code review guidelines for agents

---

src/fastmcp/server/elicitation.py
tests/client/test_elicitation.py

Fixes #1565
Python enums in elicitation requests were generating JSON schemas with `$ref/$defs` references, causing them to display as free-text inputs instead of dropdowns in Claude Desktop and VS Code.
This PR introduces a custom `ElicitationJsonSchema` generator that ensures enums are always inlined directly in the schema, making them compatible with MCP's elicitation requirements. As a bonus, it adds `enumNames` support for better UI display (e.g., "Not Started" vs "not_started").
The approach generates correct schemas from the start rather than post-processing, making it cleaner and more maintainable than alternative solutions.
Note: The MCP Inspector appears to hang when testing multiple elicitations, but we've validated this works correctly with a FastMCP Client.

Fix enum elicitation to use inline schemas for MCP compatibility

---

docs/servers/auth/oauth-proxy.mdx
src/fastmcp/server/auth/oauth_proxy.py
tests/server/auth/test_oauth_proxy.py

Extends `ProxyDCRClient` creation in `OAuthProxy` to set the default scope.
---

Add default scope handling in OAuth proxy

---

docs/integrations/google.mdx
src/fastmcp/server/auth/oauth_proxy.py

Google requires Google-specific scope URLs

Update documentation around scopes for google

---

README.md

Update result printing in README example

---

docs/docs.json
docs/integrations/auth0.mdx
docs/servers/auth/oidc-proxy.mdx
src/fastmcp/server/auth/oidc_proxy.py
src/fastmcp/server/auth/providers/auth0.py
tests/server/auth/providers/test_auth0.py
tests/server/auth/test_oidc_proxy.py

Add support for OIDC configuration to simplify integrating providers that support it.
The `OIDCProxy` class wraps `OAuthProxy` to use the dynamic values available from provider's configuration URL for the client application.
This also includes an `Auth0` implementation that uses `OIDCProxy`.
I did my best to follow existing patterns in the codebase and am happy to make any suggested changes.
I did not update the `Python SDK` docs as I believe that is done automagically from the committed code. I also set the `VersionBadge` values to `2.13.0` as I am assuming if this is accepted it would be for a larger release.
---

feat: Add support for OIDC configuration

---

src/fastmcp/server/http.py

#1812 had an extraneous union import that failed static tests but I couldn't push directly to the branch, so fixing here.

Remove extraneous union import

---

src/fastmcp/server/server.py
tests/server/test_server.py

Refs: https://github.com/jlowin/fastmcp/issues/1837
Allow instructions to be set in code.
---

feat: Set instructions in code

---

README.md

Update dark mode image in README

---

src/fastmcp/server/auth/auth.py
src/fastmcp/server/http.py
tests/server/auth/test_remote_auth_provider.py

Handling [issue](https://github.com/jlowin/fastmcp/issues/1836) 
---

Fix: get_resource_url nested URL handling

---

.pre-commit-config.yaml
docs/changelog.mdx
pyproject.toml
src/fastmcp/contrib/mcp_mixin/README.md
tests/client/test_client.py

Fix typos discovered by codespell and add codespell to pre-commit.
* https://pypi.org/project/codespell
---

Fix typos discovered by codespell

---

.github/workflows/marvin-dedupe-issues.yml
.github/workflows/marvin-label-triage.yml
.github/workflows/marvin.yml

Marvin seems unable to locate the correct permissions for certain actions, this should (?) help

Improve env vars for marvin
