.github/workflows/run-tests.yml
.gitignore
examples/text_me.py

adds example using https://surgemsg.com/ to text myself from claude
```console
fastmcp install examples/text_me.py -f .env && fastmcp run examples/text_me.py
```
also updates tests to only run on changes to src, tests, and dep-related files

Surge example

---

README.md
examples/screenshot.py
src/fastmcp/cli/claude.py
src/fastmcp/cli/cli.py
src/fastmcp/server.py
tests/test_cli.py

When developing and deploying a server, we want to be able to specify Python dependencies without having to do `--with dep` every time. 
In earlier versions of FastMCP, it was possible to use uv's [script dependencies] (https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies) to declare dependenceis as frontmatter, but since we now use `fastmcp run server.py` instead of `uv run server.py` by default, they don't get parsed.
This PR makes the following code possible (which requires pandas) while keeping the install command `fastmcp install demo.py`
```python
mcp = FastMCP("demo", dependencies=['pandas']
@mcp.tool()
def demo():
import pandas
...
```
The README is also updated to clarify that:
- `fastmcp install` will respect server dependencies …

Support Python dependencies in Server

---

Windows_Notes.md
src/fastmcp/cli/cli.py
tests/resources/test_file_resources.py
tests/test_cli.py

This fixes _parse_file_path for windows users.  Also fixes 1 test, and adds 3 more for this function.
I did have to bypass 1 file permissions test on windows because I couldn't get it to fail permissions properly.

Changes to accomodate windows users.

---

Windows_Notes.md
src/fastmcp/cli/cli.py
tests/test_cli.py

This PR fixes 2 issues:
1) The dev action in cli.py could not find node or npx in the running processes due to the way they are called and managed.  Added additional code for windows that checks for node/npx properly. This required an OS aware test change.  Windows calls for npx subprocess twice, and unix only once.  The test was only expecting once in all occasions.
2) If a MCP server included modules, the cli would fail to build them because it wouldn't do it from the root of the mcp server being built.  Added short code to add parent directory to path if not already there.

Additional Windows Fixes for Dev running and for importing modules in a server

---

README.md
examples/complex_inputs.py
src/fastmcp/exceptions.py
src/fastmcp/tools/base.py
src/fastmcp/utilities/func_metadata.py
tests/test_func_metadata.py
tests/test_tool_manager.py

This updates tools to handle complex function arguments including
- Pydantic models
- Things like `list[str] | str`
- Things like `Annotated[str, Field(max_length=10)]`
A key part of this is that there's pre-processing to parse inputs from the client from JSON.
This is because Claude Desktop seems to send complex things - sub-models, lists of strings - as JSON strings. If you naively try to validate them with pydantic they'll fail because they're just strings.
The code here is conceptually very similar to FastAPI
- See [`analyze_param`](https://github.com/fastapi/fastapi/blob/8255edfecfe539f09c2655016ea3ef3e4fb50881/fastapi/dependencies/utils.py#L348)
- See [`request_params_to_args`](https://github.com/fastapi/fastapi/blob/8255edfecfe539f09c2655016ea3ef3e4fb50881/fastapi/dependencies/utils …

Handle complex inputs

---

pyproject.toml
tests/test_cli.py
tests/test_func_metadata.py
uv.lock

see warnings and failures https://github.com/jlowin/fastmcp/actions/runs/12131427611
- fix pytest warnings "cannot collect" `TestClassNotGroupingCases` -> `SomeClassNotGroupingCases`
- order-independent check for `test_dev_with_dependencies`
- adds `pytest-flakefinder` as a dev dep so I can do
```
» pytest tests/test_cli.py -k with_dep --flake-finder
tests/test_cli.py ....................................................................................................    [100%]
======= 100 passed, 600 deselected in 0.84s ======
```

fix warning and flake

---

src/fastmcp/utilities/logging.py

Without this, logs get sent to stdout which is captured by the
JSONRPC protocol (which also causes some errors with clients when
the invalid JSON is sent over the stdout pipe).

fix: use stderr for logging

---

LICENSE

FastMCP's code will be merged into the main MCP codebase, which is MIT licensed. To facilitate that, I am relicensing the codebase as MIT. 
This will be part of a new 0.4 release for clarity.

Relicense from Apache 2.0 to MIT

---

src/fastmcp/utilities/func_metadata.py
tests/test_func_metadata.py

fix: handle strings containing numbers correctly

---

src/fastmcp/utilities/func_metadata.py

Looks like `try_eval_type` was only added recently https://github.com/pydantic/pydantic/commit/bcfd413926fbc1221fe80b302fe3bbba56840216 so switching to the older (and now deprecated) `eval_type_lenient`
When I did #31 I saw FastAPI was using `eval_type_lenient` and I figured hey why not use the non-deprecated version of it. Well now I know - because it's not in earlier pydantic versions 😇

Avoid new try_eval_type unavailable with older pydantic

---

src/fastmcp/server.py

This PR modifies how FastMCP handles SSE message endpoints by using Starlette's `Mount` instead of `Route`. This change follows the recommended approach from the MCP SDK team as discussed in [modelcontextprotocol/python-sdk#83](https://github.com/modelcontextprotocol/python-sdk/pull/83).
When using FastMCP with SSE transport, users encounter a `TypeError: 'NoneType' object is not callable` error. This occurs because:
1. The current implementation uses a Starlette `Route` for handling SSE messages
2. `SseServerTransport.handle_post_message` is designed as a full ASGI application
3. Starlette's `Route` expects handlers to return a response object, but our handler doesn't
Following the guidance from @jspahrsummers in [python-sdk#83](https://github.com/modelcontextprotocol/python-sdk/pull/83), …

fix: use Mount instead of Route for SSE message handling

---

README.md
examples/mount_example.py
pyproject.toml
src/fastmcp/client/client.py
src/fastmcp/client/transports.py
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
src/fastmcp/utilities/func_metadata.py
src/fastmcp/utilities/openapi.py
tests/utilities/openapi/test_openapi.py
tests/utilities/openapi/test_openapi_advanced.py
tests/utilities/openapi/test_openapi_fastapi.py
uv.lock

- reinstate installing `dev` on `uv sync`
- use https://github.com/ninoseki/uv-dynamic-versioning/tree/main instead of hatch-vcs
- fix deprecated instance methods calls of `model_fields`

fix deprecation warnings

---

examples/mount_example.py
src/fastmcp/cli/cli.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
tests/server/test_mount.py

Closes #126 
A few people reported a bug that Claude does not support `/` in tool names, which was part of the default prefix for mounted sub-MCP's. 
This PR updates the default separator to `_` and exposes configuration for customizing this, as requested in #126.

Change default mounted tool separator from / to _

---

docs/servers/fastmcp.mdx
src/fastmcp/cli/cli.py
src/fastmcp/server/server.py
tests/cli/test_run.py
uv.lock

supports e.g. `mcp.run(transport='sse', host=<>, port=<>)` and also `fastmcp run file.py --host <> --port <>`
Closes #158 and supersedes #148

Add transport kwargs for mcp.run() and fastmcp run

---

src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_manager.py
tests/server/test_mount.py
tests/server/test_server.py
tests/tools/test_tool_manager.py

Avoids copying tools during import by using a custom name to reference them without changing the underlying tool name. Ensures that Proxy tools can be imported successfully.

Allow tool manager to store an alternative name for tools

---

src/fastmcp/resources/resource.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/resources/template.py
src/fastmcp/server/server.py
tests/client/test_client.py
tests/resources/test_resource_template.py

- Generate MCP resources/templates on the relevant object rather than the server
- Fix bug in template matching introduced in #170

Generate MCP resources and templates on respective classes

---

docs/patterns/fastapi.mdx
docs/patterns/openapi.mdx
pyproject.toml
src/fastmcp/server/server.py
uv.lock

Removes FastAPI as a dependency since it was only used to type a keyword argument. Retains it as a development dependency for tests.

Improve integration documentation

---

docs/getting-started/quickstart.mdx

The example in the documentation shows the `@mcp.tool` decorator without parentheses, which leads to a runtime error:
`TypeError: The @tool decorator was used incorrectly. Did you forget to call it? Use @tool() instead of @tool`
This PR adds the missing parentheses (`@mcp.tool()`) in the usage example to avoid confusion and ensure the example works out of the box.

Fix missing parentheses in `@mcp.tool` decorator example

---

pyproject.toml
uv.lock

This patch swaps out the deprecated dotenv package v0.9.9 with the actively maintained python-dotenv v1.1.0

Replace deprecate `dotenv` with supported `python-dotenv`

---

src/contrib/mcp_mixin/README.md
src/contrib/mcp_mixin/__init__.py
src/contrib/mcp_mixin/example.py
tests/contrib/test_mcp_mixin.py

Allow usage of mcp_mixin via 
```
from contrib.mcp_mixin import MCPMixin, mcp_tool, mcp_resource
```

Add an init to make mcp_mixin a module

---

src/fastmcp/server/server.py
tests/cli/test_run.py

Kwargs such as host/port were not being passed properly to anyio.run. Closes #201.

Pass kwargs correctly

---

src/fastmcp/client/client.py
src/fastmcp/server/proxy.py
tests/client/test_client.py

Fix two issues with proxy mcp server, let me know if you want to separate into two PRs:
1. tolerate METHOD_NOT_FOUND error, because the legacy server might not support all methods
2. Fix nested client context manager behavior which is important for proxy server use case.
```python
with Client(...) as client:
proxy_mcp = MCPServer.from_client(client)
await proxy_mcp.list_tools()
```

fix issues with proxy mcp server

---

docs/servers/resources.mdx
src/fastmcp/resources/template.py
tests/resources/test_resource_template.py

Closes #245 
Allows resource templates to have wildcard parameters that include multiple path segments, e.g.
```python
@mcp.resource('repo://{owner}/{repo}/{file*}')
def repo_file(owner:str, repo:str, file: str):
...
```
This would match e.g. `"repo://jlowin/fastmcp/src/fastmcp/main.py"` as `{"owner": "jlowin", "repo": "fastmcp", "path": "src/fastmcp/main.py"}`

Add wildcard params for resource templates

---

src/fastmcp/utilities/func_metadata.py
tests/utilities/test_func_metadata.py

The function tries to convert `str` into `dict` without validate if it is suitable for the type annotation.
This will cause unintended type converting.
Fixes: #251

fix: unintended type convert

---

src/fastmcp/server/openapi.py
tests/server/test_openapi.py

If an OpenAPI Resource/ResourceTemplate returns a non-str response, it causes an MCP error. This wasn't caught because we were testing the low-level functionality without instantiating a full MCP server. 
Now GET requests (or other custom Resource routes) will automatically be coerced to str / bytes depending on the response type.
Closes #195

Ensure openapi resources return valid responses

---

docs/servers/context.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
src/fastmcp/prompts/prompt.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/resources/template.py
src/fastmcp/resources/types.py
src/fastmcp/server/openapi.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
tests/server/test_server_interactions.py

Resources, resource templates, and prompts can all receive the MCP context (and access its advanced features) by adding a function argument annotated as `fastmcp.Context`. This will automatically receive the context object when the object is invoked.
Closes #134
```python
from fastmcp import FastMCP, Context
mcp = FastMCP(name="MyServer")
@mcp.tool()
async def my_tool(x: int, ctx: Context) -> str:
return f"Tool called with {x}"
@mcp.resource("resource://{id}")
async def get_resource(id: str, ctx: Context) -> str:
return f"Resource {id}"
@mcp.prompt()
async def my_prompt(question: str, ctx: Context) -> str:
return f"Prompt called with {question}"
```

Support context injection in resources, templates, and prompts (like tools)

---

src/fastmcp/server/openapi.py
tests/server/test_openapi.py

The implementation now correctly handles multiple path parameters in OpenAPI endpoints. Previously, only the last parameter was recognized, leading to incorrect behavior when accessing resources with multiple parameters. The changes include updates to the parameter extraction logic and the addition of tests to ensure proper functionality. This addresses issue https://github.com/jlowin/fastmcp/issues/267.

#267 Fix openapi template resource to support multiple path parameters

---

src/fastmcp/server/openapi.py
src/fastmcp/server/proxy.py
tests/server/test_openapi.py

Closes #275, supersedes #277 
If an openapi tool returned a list, it was not properly converted to an MCP response. This ensures _convert_to_content is always called.

Ensure openapi tool responses are properly converted

---

src/fastmcp/prompts/prompt.py
src/fastmcp/resources/types.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
tests/resources/test_function_resources.py
tests/resources/test_resource_template.py
tests/server/test_mount.py
tests/server/test_server_interactions.py
tests/tools/test_tool_manager.py

Analogue of https://github.com/modelcontextprotocol/python-sdk/pull/545

use pydantic_core.to_json

---

docs/clients/client.mdx
src/fastmcp/client/client.py
src/fastmcp/contrib/bulk_tool_caller/bulk_tool_caller.py
src/fastmcp/server/proxy.py
tests/client/test_client.py
tests/server/test_server_interactions.py

Supports "friendly" client behavior like `client.call_tool()` or returning the "raw" MCP objects via `client.call_tool_mcp()`.
Closes #295

Add low-level methods to client

---

docs/servers/context.mdx
src/fastmcp/server/context.py

Fast follow to rename new method in #302

get_starlette_request → get_http_request

---

examples/serializer.py
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_manager.py
tests/tools/test_tool_manager.py

Example for #207
running the example prints:
```
Tool Result:
[TextContent(type='text', text='name: Test\nvalue: 123\nstatus: true\n', annotations=None)]
```

Support custom Serializer for Tools

---

docs/patterns/composition.mdx
docs/servers/fastmcp.mdx
src/fastmcp/server/server.py
tests/server/test_mount.py

Closes #305 by supporting converting mounted servers to proxies via a new `as_proxy` flag. FastMCP servers that have lifespans are automatically converted to proxies unless the user specifies as_proxy=False.
Incidentally I've noticed in this that the low-level server seems to never close the lifespan properly? Post-yield hooks aren't called. i think this might be related to the issue discussed in #296 and needs investigation, though I think the problem is in how low-level server.run() is invoked.

Support proxy mount

---

docs/patterns/composition.mdx
docs/servers/fastmcp.mdx
src/fastmcp/tools/tool.py
tests/tools/test_tool_manager.py

Currently if a tool_serializer is provided that doesn't handle the returned tool result (e.g. a non-JSONable object), it errors and breaks the server. This falls back to the default in that case to avoid breaking.

Ensure that tool serialization has a graceful fallback

---

docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
tests/prompts/test_prompt_manager.py
tests/resources/test_resource_template.py
tests/server/test_server_interactions.py
tests/tools/test_tool.py
tests/tools/test_tool_manager.py

Closes #313 
This PR:
- prevents registering tools with *args / **kwargs (because no sensible parameter schema can be generated)
- prevents registering templates with *args but allows **kwargs (because parameter names are inferred from the URI template)
- prevents registering prompts with *args / **kwargs

Handle *args/**kwargs appropriately for various components

---

docs/clients/client.mdx
docs/servers/prompts.mdx
src/fastmcp/client/client.py
src/fastmcp/prompts/__init__.py
src/fastmcp/prompts/prompt.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
tests/client/test_client.py
tests/prompts/test_prompt.py
tests/prompts/test_prompt_manager.py
tests/server/test_import_server.py
tests/server/test_proxy.py
tests/server/test_server.py
tests/server/test_server_interactions.py

Inspired by https://github.com/modelcontextprotocol/python-sdk/pull/614 and would close https://github.com/modelcontextprotocol/python-sdk/issues/602. 
This ensures that everything include FastMCP clients return the full prompt object and highlights an important potential for breaking changes as user-facing client methods may need adjusting as the protocol evolves. Appropriate warnings have been added to the documentation about the difference between user-facing and `*_mcp` methods in the `Client` object.

Ensure prompts return descriptions

---

src/fastmcp/tools/tool.py
src/fastmcp/utilities/types.py

Closes #330 
This PR is a hotfix for #330 because the behavior is pathological. A full fix will probably require removing the auto-json parsing to ensure we don't inadvertently introduce other related edge cases (such as turning the literal string `"true"` into a bool).
The cause of the issue is an old (dating to v1) behavior that attempts to parse all tool arguments to JSON before passing them to the tool. This is because Claude Desktop tends to send stringified JSON instead of proper objects. However, this means that JSON-like arguments (such as stringified integers) are converted into integers. Pydantic does not automatically convert integers into strings (it did in v1, it does not in v2), which created this unexpected conversion error. As a temporary solution I am enabling number to …

Coerce numbers to str

---

src/fastmcp/server/http.py
src/fastmcp/server/server.py

Refactor in preparation for streamble http

Move sse app to http

---

src/fastmcp/tools/tool.py
tests/tools/test_tool_manager.py

Fix tool result serialization when the tool returns a list

---

docs/getting-started/installation.mdx
docs/getting-started/quickstart.mdx
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py

Hi,
As title says, fixing various typos found when reading the docs.
For details, see commit diff.
BTW, fastmcp is great! Thks for that
Didier

Fixing various text typos

---

docs/deployment/asgi.mdx
docs/deployment/running-server.mdx
docs/docs.json
pyproject.toml
src/fastmcp/low_level/README.md
src/fastmcp/low_level/sse_server_transport.py
src/fastmcp/server/http.py
tests/client/test_sse.py
tests/client/test_streamable_http.py

Closes #365
Closes #370
Closes #382
Closes #234
Closes #225
Closes #189
Addresses the following low-level / FastMCP 1.0 issues: https://github.com/modelcontextprotocol/python-sdk/issues/673, https://github.com/modelcontextprotocol/python-sdk/issues/563, https://github.com/modelcontextprotocol/python-sdk/issues/507, https://github.com/modelcontextprotocol/python-sdk/issues/464, https://github.com/modelcontextprotocol/python-sdk/issues/412
Since it is unclear if the low-level SDK will merge https://github.com/modelcontextprotocol/python-sdk/pull/659, we are adding a patched low-level SSETransport to FastMCP (and can remove it if/when the bug is fixed). This should resolve issues with nested ASGI applications. 
However, note that you **must** pass the MCP lifespan to the outer-most app, due …

Ensure FastMCP handles nested SSE and SHTTP apps properly in ASGI frameworks

---

src/fastmcp/tools/tool.py

When an exception happens in a tool, most of the details are dropped including stack traces, which makes debugging pretty challenging. The PR is to add a logging for exceptions at the low level to capture what's happening properly.
I'd be happy to update it to generalize the solution if the maintainer can give more guidance.

logging stack trace for easier debugging

---

src/fastmcp/server/server.py
src/fastmcp/settings.py
src/fastmcp/utilities/logging.py
tests/test_deprecated.py

Adds a deprecation notice but does not change behavior. In the future, transport-specific settings will not be provided via the FastMCP constructor; only settings related to the server's universal operation will be accepted. This is to avoid the reasonable confusion in cases like #419, and more broadly to avoid the apparent trend of FastMCP becoming a dumping group for configuration (this is definitely the case in 1.x, and many of these settings are holdovers from that approach, in addition to new ones like streamable http)

Deprecate passing settings to the FastMCP instance

---

src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
tests/server/test_server.py
tests/tools/test_tool_manager.py

Adds support for removing tools from the server at runtime.
This allows users to dynamically remove tools based on internal state or external logic, as suggested in issue #433
- Added `ToolManager.remove_tool(key: str)`
- Added `FastMCP.remove_tool(name: str)` as a public API
- Cleared tool cache to maintain consistency
- Added unit tests to both ToolManager and FastMCP test suites
- Method names and docstrings match existing project conventions
- Exception handling is consistent with other FastMCP behavior
All tests pass, and `pre-commit` checks are clean.

feat: add support for removing tools from server

---

src/fastmcp/server/openapi.py
tests/server/test_openapi.py
tests/utilities/openapi/test_openapi_fastapi.py

OpenAPI object reprs hit recursion errors, so we create them by hand.

Add reprs for OpenAPI objects

---

src/fastmcp/utilities/json_schema.py
tests/utilities/test_json_schema.py

Closes #412 by pruning 'title' fields from all generated jsonschemas

Prune titles from JSONSchemas

---

src/fastmcp/server/server.py

This PR updates the stdio version of the `FastMCP` server to declare the `tools/list_changed` capability, as defined in the MCP spec.  Related to #439. 
- The [MCP spec](https://modelcontextprotocol.io/specification/2025-03-26/server/tools#list-changed-notification) states: *"When the list of available tools changes, servers that declared the `listChanged` capability SHOULD send a notification."*
- Declaring `listChanged = True` signals to clients that this server may notify them when the tool list changes.
- It does not require immediate notification support, nor does it change any current behavior.
- The server still does not send `tools/list_changed` notifications when tools are added or removed.
- Emitting those would require access to an active session, which is not currently …

Declare toolsChanged capability for stdio server.

---

src/fastmcp/client/client.py
src/fastmcp/client/transports.py
src/fastmcp/settings.py
src/fastmcp/utilities/exceptions.py
tests/server/test_openapi.py
tests/server/test_proxy.py
tests/server/test_server.py
tests/server/test_server_interactions.py
tests/tools/test_tool.py

Currently, we are naively raising taskgroup ExceptionGroups which give messy and complicated ASCII tracebacks. This modifies client behavior to raise the first group in each exception group. The setting is configurable in case there is a situation where this degree of visibility is undesireable because it masks multiple errors, but that is unexpected.

Improve handling of exceptiongroups when raised in clients

---

.github/workflows/run-tests.yml
uv.lock

Because we were not setting the uv python version, `uv sync` was reverting to 3.12

Ensure tests run against correct python version

---

.github/workflows/run-tests.yml
docs/clients/client.mdx
src/fastmcp/client/client.py
src/fastmcp/client/transports.py
src/fastmcp/exceptions.py
src/fastmcp/utilities/exceptions.py
tests/client/test_client.py
tests/client/test_sse.py
tests/client/test_streamable_http.py

Timeouts can be supplied either when instantiating the Client OR on specific tool calls. Closes #442

Add timeout support to client

---

src/fastmcp/server/server.py

I'm using a middleware on a project, and I could use a quicker way to add one from run instead of creating a new app using `mcp.http_app`.
LMK if there's something I forgot to do here.

feat: Add middleware option in server.run

---

tests/client/test_client.py

This PR addresses #474 by increasing the client timeout in `TestTimeout::test_timeout` from 0.01s to 0.05s.
**Background:**  
With the original 0.01s timeout, the test would occasionally fail due to event loop scheduling and system timing, as confirmed by running:
```sh
pytest tests/client/test_client.py::TestTimeout::test_timeout --count=5000
```
Results:
- timeout=0.01s: 1 failure in 5,000 runs
- timeout=0.05s: 0 failures in 5,000 runs
**Rationale:**  
A slightly longer timeout gives the event loop enough time to enforce it reliably, making the test more robust.

Fix flaky timeout test by increasing timeout (#474)

---

docs/deployment/asgi.mdx
src/fastmcp/server/http.py
src/fastmcp/server/server.py
tests/client/test_streamable_http.py

Alternative to #481 that would also close #480 
The approach taken in #481 exposes an implementation detail of the upstream SDK as part of FastMCP's public API. I'm not a huge fan of the fact that the session manager already requires lifespan management, creating headaches for users since that can't be done automatically, and hope the upstream SDK will change (or FastMCP will reimplement separately). Consequently I don't like exposing that implementation detail to our users, as there is no need to access the session manager except to get its lifespan and if the upstream changes it will require us to make a breaking change to our API.
In addition, #481 would still require users to understand that the session manager's `run` method needs to be placed inside an async context manager, which …

Add lifespan property to app

---

docs/deployment/asgi.mdx
src/fastmcp/server/http.py
tests/server/test_app_state.py

- store the FastMCP instance under `app.state.fastmcp_server`
- update ASGI deployment docs to reference the new state name
- adjust tests for updated state name
Closes #487 
(note: asked Codex to handle this bc seemed straightforward)

Store FastMCP instance on app.state.fastmcp_server

---

docs/deployment/cli.mdx
src/fastmcp/cli/cli.py
src/fastmcp/cli/run.py
src/fastmcp/server/http.py
src/fastmcp/server/server.py
tests/cli/test_cli.py
tests/cli/test_run.py

`fastmcp run https://example.com/mcp` will proxy the remote server using the specified transport. Can be used to e.g. connect a remote server to Claude Desktop with one line.

Update `fastmcp run` to work with remote servers

---

README.md
docs/servers/composition.mdx
docs/servers/fastmcp.mdx
docs/servers/proxy.mdx
examples/in_memory_proxy_example.py
src/fastmcp/server/server.py
tests/server/test_import_server.py
tests/server/test_mount.py
tests/server/test_proxy.py
tests/test_deprecated.py

NOTE: will change documentation in a breaking way; delay release.
- add `FastMCP.as_proxy` classmethod for creating proxy servers
- deprecate `FastMCP.from_client`
- update docs and example for new API
- adjust tests to use `as_proxy`

Add FastMCP.as_proxy()

---

tests/resources/test_file_resources.py

This fixes:
- #501
I have added a check `or os.getuid() == 0` to the skipping condition of the test to make sure it is skipped when running as root.

Skipping `test_permission_error` if runner is root.

---

tests/client/test_client.py
tests/client/test_sse.py
tests/client/test_streamable_http.py

@zzstoatzz what do you think? These tests are flaky. I do wonder if it's a timing thing, like if we increased the timeouts to ~1 second it would have enough time to properly respond, but I don't want to add such overhead to the test suite. Maybe only on windows we use higher timeouts? Happy to merge this now regardless.

Skip timeout tests on windows

---

src/fastmcp/client/client.py
src/fastmcp/client/transports.py
tests/client/test_client.py
tests/server/test_server_interactions.py

Closes #500
When creating a client session, we now store the initialize result so users can access it as `client.initialize_result` within the `async with Client()` context manager. Outside the client, it will error.

Store the initialize result on the client

---

docs/patterns/openapi.mdx
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
tests/server/test_openapi.py

This PR permits custom RouteMaps to absorb all HTTP Methods by providing `RouteMap(methods='*')`, and also adds a new `all_routes_as_tools` kwarg when converting OpenAPI and FastAPI apps.

Allow * Methods and all routes as tools shortcuts

---

src/fastmcp/client/client.py

Based on https://github.com/modelcontextprotocol/python-sdk/issues/332
This does *not* universally solve hanging issues with STDIO, of which there are many! See e.g. #499. But it does solve a common one in which the initial handshake fails.

Avoid hanging on initializing server session

---

docs/servers/composition.mdx
src/fastmcp/server/server.py
tests/deprecated/test_deprecated.py
tests/deprecated/test_mount_separators.py
tests/server/test_import_server.py
tests/server/test_mount.py
tests/server/test_openapi.py
tests/server/test_server.py

This is technically a breaking change because it removes user-customizable separators when mounting servers under a prefix. However, these customizable prefixes caused a problem for resources in particular because the resource prefix became part of the URI protocol, which has even more restrictions than other parts of the URI (like the path). For example, if you mounted a server with the prefix `"sub_server"` it would fail because protocols can't have underscores. 
This PR modifies resource prefixes to become part of the path not the protocol. In other words, `protocol://path/to/resource` becomes `protocol://prefix/path/to/resource` in the new setup, which is far more natural. On the plus side this improves our support for arbitrary prefix mounts.
As an extension, customziable separators …

Remove customizable separators; improve resource separator

---

docs/servers/composition.mdx
src/fastmcp/server/server.py
src/fastmcp/settings.py
tests/deprecated/test_resource_prefixes.py
tests/server/test_resource_prefix_formats.py

#526 introduced a new resource prefix format. To avoid compatibility issues, this PR allows users to use the legacy format by setting global config
```python
import fastmcp
fastmcp.settings.settings.resource_prefix_format = "protocol" 
```
or on a per-server basis
```python
server = FastMCP("LegacyServer", resource_prefix_format="protocol")
```
The available options are `"path"` (new default) or `"protocol"` (legacy behavior).

Make resource prefix format configurable

---

docs/clients/client.mdx
docs/clients/transports.mdx
src/fastmcp/client/transports.py
tests/client/test_client.py

- support FastMCP 1.0 server objects in `FastMCPTransport` and `infer_transport`
- document FastMCP 1.0 compatibility
- test transport inference with FastMCP 1.0 servers
- `uv run pre-commit run --all-files`
- `uv run pytest`

Add FastMCP 1.0 server support for in-memory Client / Testing

---

docs/servers/context.mdx
src/fastmcp/server/context.py
tests/server/test_context.py

This PR addresses #524 by exposing the `model_preferences` parameter in the `Context.sample` method. This allows server authors to specify model selection preferences—such as model hints or a full `ModelPreferences` object—when requesting LLM sampling from the client.
- Added `model_preferences` parameter to `Context.sample`, supporting:
- A string (single model hint)
- A list of strings (multiple model hints)
- A `ModelPreferences` object (for [advanced use](https://modelcontextprotocol.io/specification/2025-03-26/client/sampling#model-preferences))
- Added robust input validation and conversion logic.
- Updated documentation and usage examples to reflect the new parameter.
- Added unit tests for all supported input types and error cases.
- Updated the docs to include the new parameter …

Expose model preferences in `Context.sample` for flexible model selection.

---

src/fastmcp/client/client.py

- Implements `Client.cancel()` to emit `notifications/cancelled` as defined in the [spec](https://modelcontextprotocol.io/specification/2025-03-26/basic/utilities/cancellation#cancellation)
- Allows clients to request cancellation of in-progress requests with an optional reason.
- No tests added, matching current notification method coverage.
Happy to close if there's another way to do this. Didn't see the option anywhere else.

Add client method to send cancellation notifications

---

README.md
docs/getting-started/welcome.mdx
docs/servers/openapi.mdx
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
tests/server/openapi/test_route_map_fn.py

Adds `route_map_fn` (which allows fine-grained customization of RouteMaps assignments) and `mcp_component_fn` (which allows fine-grained customization of generated MCP components) for advanced customization of OpenAPI integrations

Add advanced control of openAPI route creation

---

docs/servers/openapi.mdx
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
tests/client/test_openapi.py
tests/server/openapi/test_openapi.py
tests/server/openapi/test_openapi_path_parameters.py

This PR changes how OpenAPI component names are generated (generally improving them) and permits name customization by providing an `mcp_names` dictionary to `from_openapi()` or `from_fastapi()`. The dictionary maps OpenAPI operation IDs to MCP component names.
In addition, it automatically slugifies and truncates all names to 56 characters.
Users can also use the mcp component fn introduced in #566 
Closes #420 
Closes #188

Permit more flexible name generation for OpenAPI servers

---

docs/patterns/http-requests.mdx
src/fastmcp/client/transports.py
src/fastmcp/server/dependencies.py
src/fastmcp/server/openapi.py
tests/client/test_openapi.py

Ensure content-length is always stripped from client headers

---

docs/patterns/http-requests.mdx
src/fastmcp/server/dependencies.py
tests/client/test_openapi.py

Ensure behavior-affecting headers are excluded when forwarding proxies/openapi

---

src/fastmcp/client/client.py
tests/server/test_proxy.py

Fixes: https://github.com/jlowin/fastmcp/issues/533
Reworked session state management in the client to use a background task, mirroring the approach used in StdioTransport. This resolves issues with session consistency and lifecycle that could arise when multiple clients are using `async with client` (i.e. in FastMcpProxy).
Added tests to demonstrate the issue which can be run prior to any code changes.

fix: Support concurrency in FastMcpProxy (and Client)

---

src/fastmcp/utilities/tests.py
tests/auth/test_oauth_client.py
tests/client/test_openapi.py
tests/client/test_sse.py
tests/client/test_streamable_http.py
tests/server/http/test_http_dependencies.py

Since servers aren't pickleable, we want a very clean and minimal DX (but still customizable) for running them for tests. We already had a few good steps in this direction, this goes farther. Now this is recommended:
```python
def run_server(host: str, port: int, **kwargs) -> None:
server = FastMCP()
fastmcp_server().run(host=host, port=port, **kwargs)
@pytest.fixture(scope='module')
def shttp_server() → str:
with run_server_in_process(run_server) as url:
yield url
def my_test(shttp_server: str):
async with fastmcp.Client(shttp_server) as client:
...
```

Simplify code for running servers in processes during tests

---

src/fastmcp/utilities/openapi.py
tests/utilities/openapi/test_openapi.py

openapi's put resuable data structures under `#/components/schemas/`
but json schema put the same structures under `#/$defs/`
when using `FastMCP.from_fastapi(...)`, some nested pydantic model still have "$ref: #/components/schemas/ModelName" in the `inputSchema`, making it unable to resolve.
---
the `def _combine_schemas` function takes care of some scenarios (flat $ref in query params)
this PR makes query params and body support nested models

replace $ref pointing to `#/components/schemas/` with `#/$defs/`

---

README.md
docs/servers/context.mdx
docs/servers/fastmcp.mdx
docs/servers/prompts.mdx
src/fastmcp/server/server.py
tests/client/test_client.py
tests/client/test_sse.py
tests/client/test_streamable_http.py
tests/deprecated/test_deprecated.py
tests/deprecated/test_mount_separators.py
tests/server/http/test_http_dependencies.py
tests/server/test_import_server.py
tests/server/test_mount.py
tests/server/test_proxy.py
tests/server/test_run_server.py
tests/server/test_server.py
tests/server/test_server_interactions.py
tests/test_servers/fastmcp_server.py

This change allows the server.prompt decorator to be used in all common invocation forms, including:
• @server.prompt (bare decorator)
• @server.prompt() (empty call)
• @server.prompt("name") (positional name)
• @server.prompt(name="name") (keyword name)
• server.prompt(func, name="name") (direct function call)
Also supports optional description and tags for richer tool metadata.
This is far more Pythonic, in particular the bare decorator.

Allow naked prompt decorator

---

README.md
docs/clients/transports.mdx
docs/deployment/asgi.mdx
docs/deployment/running-server.mdx
docs/getting-started/quickstart.mdx
docs/getting-started/welcome.mdx
docs/integrations/anthropic.mdx
docs/integrations/claude-desktop.mdx
docs/integrations/gemini.mdx
docs/integrations/openai.mdx
docs/patterns/cli.mdx
docs/patterns/decorating-methods.mdx
docs/patterns/http-requests.mdx
docs/patterns/testing.mdx
docs/servers/auth/bearer.mdx
docs/servers/composition.mdx
docs/servers/context.mdx
docs/servers/fastmcp.mdx
docs/servers/prompts.mdx
docs/servers/proxy.mdx
docs/servers/tools.mdx

Until 2.7 is out, we need to leave the empty parens in the documentation! This can be reverted when 2.7 is released.

Add empty parens to docs

---

src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/tools/tool.py
tests/utilities/test_typeadapter.py

Make the type checker less sad
https://github.com/jlowin/fastmcp/issues/688

Switch Pydantic defaults to kwargs

---

src/fastmcp/server/server.py

@jlowin Thanks for all the amazing work. 
I found a small issue in the documentation, likely caused by a bulk find+replace operation in this recent [commit](https://github.com/jlowin/fastmcp/commit/099d3402082b1649d3aa4698e17cd446b8918bae).

chore: fix prompt docstring

---

src/fastmcp/client/transports.py
src/fastmcp/utilities/mcp_config.py
tests/client/test_client.py
tests/server/test_proxy.py
tests/utilities/test_mcp_config.py

Closes #746 
While working on #746 I discovered a bug (or at least, an undocumented alternative feature) that passing a string to a client's `auth` kwarg added it to the Authorization header, but did not prefix it with `Bearer` as the docs state! This is fixed here and enhanced by wrapping it in a `BearerAuth` object rather than mutating the headers directly.

Fix passing token string to client auth & add auth to MCPConfig clients

---

src/fastmcp/client/client.py
src/fastmcp/client/transports.py
tests/client/test_client.py
tests/server/test_server_interactions.py

In-memory transports were inadvertently sending the initialization request twice - once in the low-level SDK and once in FastMCP. This also explains a confusing request_id increment that we couldn't understand last month!

Ensure client is only initialized once

---

src/fastmcp/client/transports.py
src/fastmcp/utilities/mcp_config.py

This PR includes two minor cleanups:
1. Redundant Import in `client/transports.py`
`MCPConfig` was being imported twice — once for direct usage and once within a `TYPE_CHECKING` block. Since it's already imported for use, the `TYPE_CHECKING` import was unnecessary and has been removed.
2. Unused Variable
The `transport = "http"` assignment was unused and has been removed to clean up the code.

MCPConfig refactor

---

src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/types.py
tests/server/test_proxy.py

Unifies all major FastMCP components under a common base class, in order to consolidate upcoming cross-component features

Create common base class for components

---

docs/getting-started/installation.mdx
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/components.py
src/fastmcp/utilities/types.py

Fast follow to #776 to create `utilities/components.py` and make `Resource` a `FastMCPComponent` subclass

Move components to own file; add resource

---

src/fastmcp/resources/resource.py
tests/resources/test_resources.py

The change in #777 reordered fields (name before uri) such that a default name could no longer be loaded from URI.

Fix field validator for resource

---

docs/patterns/tool-transformation.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
src/fastmcp/exceptions.py
src/fastmcp/prompts/prompt.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/server/proxy.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_transform.py
src/fastmcp/utilities/components.py
tests/server/test_proxy.py
tests/server/test_server_interactions.py
tests/tools/test_tool_transform.py

Add `enabled` parameter and `.enable()/.disable()` methods to tools, resources, and prompts, allowing dynamic control over component visibility and availability.
To MCP clients, disabled components do not exist and will raise "unknown {tool, resource, prompt}" errors if accessed. They do not appear in the output of `list()` calls either.
**Key Features:**
- Components can be disabled at creation time using `enabled=False` parameter
- Components can be toggled programmatically with `.disable()` and `.enable()` methods  
- Disabled components are hidden from list operations and return "Unknown" errors when accessed
- Useful for feature flagging, maintenance modes, and dynamic toolset management
**Changes:**
- Add `enabled` field and behavior to `Tool`, `Resource`, `ResourceTemplate`, and …

Support enable/disable for all FastMCP components (tools, prompts, resources, templates)

---

src/fastmcp/server/proxy.py
tests/server/test_proxy.py

This closes a small bug where if a proxy server overwrote a tool/resource/prompt (e.g. with the same name or URI), it would return the proxied component for `list` requests. `call/read/get` requests were handled correctly previously. Also ensures that disabling (#781) the locally defined tool will not fall back to the proxy

Ensure proxies can overwrite remote tools without falling back to the remote

---

docs/servers/openapi.mdx
src/fastmcp/server/openapi.py
src/fastmcp/server/server.py
tests/client/test_openapi.py
tests/server/openapi/test_openapi.py
tests/server/openapi/test_route_map_fn.py

The majority of MCP agent integrations do not support resources at this time, which means that while FastMCP's behavior of converting OpenAPI GET requests into resources is nice and arguably "correct", it almost certainly requires users to modify it in practice. 
Therefore, this PR introduces a change to the default behavior. ALL OpenAPI routes are converted to tools by default. A recipe for restoring the old behavior is provided in the documentation.

Treat all openapi routes as tools

---

src/fastmcp/utilities/json_schema.py
src/fastmcp/utilities/openapi.py
tests/utilities/openapi/test_openapi_advanced.py
tests/utilities/test_json_schema.py

I tried using FastMCP.from_openapi() on the OpenAPI definition from https://api.testing-farm.io/openapi.json 
And the resulting tool definitions failed validation by the Anthropic API because the OpenAPI file has schemas that reference other schemes, e.g.:
```json
"components": {
"schemas": {
"EnvironmentRequested": {
"properties": {
"arch": {
"$ref": "#/components/schemas/Architectures"
},
"os": {
"$ref": "#/components/schemas/Os"
},
}
}
}
```
These weren't rewritten leaving invalid dangling references in the tool definitions.
Once I added rewriting of these schemas, another problem popped up: a schema referenced only by another unused schema was now counted as referenced and not pruned - this resulted in a test failure and also bloated tool definitions, so I added a fix for that.

Openapi recursive components

---

src/fastmcp/utilities/mcp_config.py

This PR enhances the RemoteMCPServer class to support custom authentication via the httpx.Auth interface. This allows users to provide advanced or non-standard authentication mechanisms when connecting to multiple MCP servers, especially in environments where servers are secured behind API gateways using [Envoy with OPA (Open Policy Agent) sidecars](https://www.openpolicyagent.org/docs/envoy).
In some deployments, MCP servers are not directly exposed but are instead protected by API gateways and policy enforcement layers (e.g., Envoy + OPA). These setups often require custom authentication logic that cannot be satisfied by simple bearer tokens or OAuth flows. By allowing a user-supplied httpx.Auth instance, we enable seamless integration with these advanced security environments.
For …

Add httpx.Auth Support to RemoteMCPServer for Custom Authentication methods to multiple MCP Servers

---

CLAUDE.md
docs/clients/messages.mdx
docs/docs.json
docs/servers/context.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
src/fastmcp/client/client.py
src/fastmcp/client/logging.py
src/fastmcp/client/messages.py
src/fastmcp/client/transports.py
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/server/context.py
src/fastmcp/server/low_level.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
tests/client/test_notifications.py
tests/prompts/test_prompt_manager.py
tests/resources/test_resource_template.py
tests/tools/test_tool_manager.py

Implements a comprehensive notification system that automatically sends MCP list change notifications when tools, resources, or prompts are added, removed, enabled, or disabled. Includes flexible client-side message handling infrastructure.
Closes #433 
Closes #439 
Closes #437 
CLoses #451
**Automatic Notifications:**
- `notifications/tools/list_changed` when tools are modified
- `notifications/resources/list_changed` when resources/templates are modified  
- `notifications/prompts/list_changed` when prompts are modified
- Notifications only sent during active request contexts
- Deduplication via notification queue system
**Client Message Handling:**
- New `MessageHandler` class for fine-grained notification handling
- Function-based message handlers for simple use cases
- Comprehensive …

Add automatic MCP list change notifications and client message handling

---

src/fastmcp/contrib/component_manager/README.md
src/fastmcp/contrib/component_manager/__init__.py
src/fastmcp/contrib/component_manager/component_manager.py
src/fastmcp/contrib/component_manager/component_service.py
src/fastmcp/contrib/component_manager/example.py
tests/contrib/test_component_manager.py

This PR addresses the feedback from #885 by extracting the enable/disable component routes into a standalone contrib module.
Introduces a new opt-in module under `contrib/component_manager` that exposes HTTP endpoints to enable/disable **tools**, **resources**, and **prompts** at runtime.
This approach keeps the functionality available for advanced use cases (admin panels, automation workflows, etc.) without modifying the core server behavior.
- `contrib/component_manager/` – New module with setup helper and route handlers
- Full test coverage under `tests/contrib/test_component_manager.py`
- Standalone `README.md` with usage, examples, and security considerations
```python
from fastmcp.contrib.component_manager import set_up_component_manager
mcp = …
```

Component Manager

---

src/fastmcp/utilities/openapi.py
tests/utilities/openapi/test_openapi.py

**Context**
We have a very complicated `openapi.json` file, that is used for various purposes. 
Including our documentation. 
We wanna add support for things like 
- `x-cortex-mcp-enabled: False`
- `x-cortex-mcp-context: This is an llm description..`
etc.
The OpenAPI spec (and Pydantic models) already support this:
https://swagger.io/docs/specification/v3_0/openapi-extensions/
In this PR, I add support for said `extensions` and tests :)

Add OpenAPI extensions support to HTTPRoute

---

docs/clients/elicitation.mdx
src/fastmcp/client/elicitation.py
tests/client/test_streamable_http.py

If users return data from the elicitation handler, we assume they are accepting the elicitation (since data can not be provided otherwise). Minor DX benefit and skips a difficult-to-identify ElicitResult import.
Also adds a test to affirm elicitation works in stateful and stateless modes in SHTTP.

Support implicit Elicitation acceptance

---

docs/servers/auth/bearer.mdx
src/fastmcp/server/auth/providers/bearer.py
src/fastmcp/server/auth/providers/bearer_env.py

Update BearerAuthProvider to support configurable algorithms for decoding JWT Tokens. 
Closes #974

Add Support for Configurable Algorithms

---

src/fastmcp/server/server.py
src/fastmcp/settings.py
tests/client/test_streamable_http.py

Closes bug found by @jakekaplan regarding duplicate settings object

Expose stateless_http kwarg for mcp.run()

---

src/fastmcp/utilities/mcp_config.py

When using an MCPConfig (with remote servers) to initialize an MCP Client, there is no way to set the sse_read_timeout for individual servers. This PR adds that ability by adding `sse_read_timeout` to the RemoteMCPServer class

Allow per-server timeouts in MCPConfig

---

src/fastmcp/utilities/logging.py
src/fastmcp/utilities/tests.py
tests/deprecated/test_settings.py
tests/prompts/test_prompt_manager.py
tests/resources/test_resource_manager.py
tests/server/test_mount.py
tests/tools/test_tool.py
tests/tools/test_tool_manager.py

Logs were inadvertently propagated to root logger, resulting in duplicates

Avoid propagating logs

---

src/fastmcp/client/elicitation.py
src/fastmcp/client/transports.py
tests/client/test_elicitation.py
tests/client/test_openapi.py
tests/server/test_import_server.py
tests/server/test_mount.py
tests/tools/test_tool_transform.py
tests/utilities/test_mcp_config.py

Closes #1043
Ensures that we use the new ProxyClient introduced in #1022 when creating proxies for multiple clients. This permits advanced features like logging/elicitation to be forwarded to the ultimate client.

Ensure multi-client configurations use new ProxyClient

---

src/fastmcp/client/client.py

According to #1051, the context manager of the Client may cause a hang in concurrent situations. This PR refactors the methods related to the Client's context manager: 
1. Moved exception handling from `__aenter__` to `_connect`.
2. Adjusted the logic of `_connect` to ensure that the session startup is completed within `_context_lock`.
3. Adjusted the logic of `_disconnect` to ensure that the session cleanup is completed within `_context_lock`.
4. Removed unnecessary `_ready_event` settings in `_session_runner`.
These changes might seem somewhat aggressive, but I believe they should make the logic of the Client's context management clearer, thereby avoiding hard-to-detect race conditions. I would like to know your thoughts on these modifications.

Refactor Client context management to avoid concurrency issue

---

.github/ISSUE_TEMPLATE/bug.yml
pyproject.toml
src/fastmcp/cli/cli.py
src/fastmcp/cli/install/mcp_config.py
tests/cli/test_cli.py
uv.lock

Adds a convenience utility for fastmcp version: `fastmcp version --copy`
Closes #1061

Add --copy flag for fastmcp version

---

docs/patterns/cli.mdx
src/fastmcp/cli/cli.py
src/fastmcp/cli/run.py
tests/cli/test_cli.py

Add `--path` CLI option to allow users to specify the route path when running the server with HTTP or SSE transport. The default remains `/mcp/` for HTTP and `/sse/` for SSE, but users can now override this as needed.

feat: Add `--path` Option to CLI for HTTP/SSE Route

---

src/fastmcp/cli/cli.py
src/fastmcp/cli/run.py
tests/cli/test_cli.py

When refactoring the CLI in #1062, the "streamable-http" alias was inadvertently dropped as a valid transport for fastmcp run, which was a breaking change (and not one we want!). "streamable-http" and "http" are interchangeable aliases. This is a high priority fix and will be released ASAP.

Ensure the CLI accepts "streamable-http" as a valid transport

---

src/fastmcp/server/openapi.py

* Previously, when empty arrays or dictionaries were passed as parameters, they were still included in the query string as empty values.
* This pull request updates the behavior to exclude such empty parameters entirely.
For example, instead of generating query parameters like `...&arr1=&arr2=&...`, these will now be omitted.

Fix OpenAPI empty parameters

---

src/fastmcp/server/openapi.py

The exclusion of the "context" key is arbitrary and makes it impossible to interface with APIs that require a "context" key in the request body.

Do not silently exclude the "context" key from JSON body

---

docs/servers/sampling.mdx
src/fastmcp/server/context.py
tests/server/proxy/test_proxy_client.py

Add the `include_context` argument to the `Context.sample` method. The argument is passed upstream to the [MCP Python SDK](https://github.com/modelcontextprotocol/python-sdk).
Resolve #1139

Resolve #1139 -- Implement include_context argument in Context.sample

---

docs/integrations/eunomia-authorization.mdx

We have upgraded the Eunomia Authorization Middleware to subclass the native FastMCP's Middleware, therefore benefiting:
- One-line integration with FastMCP's servers
- Support for all transports
- Skip notifications requests by default
Plus, we introduced a new exciting feature:
- Act as a filter for listing operations, hiding unauthorized components to the client 🚀
Consequently, this PR **updates the relative docs page**.

Eunomia Authorization with native FastMCP's Middleware

---

src/fastmcp/server/server.py

The `test_sub_lifespan_is_executed` was raising a deprecation warning highlighting that this code path used a deprecated method of creating a Proxy server.

Remove deprecated proxy creation

---

docs/integrations/fastapi.mdx

This pull request makes a minor update to the `docs/integrations/fastapi.mdx` file, removing an unused import statement to clean up the example code.
* [`docs/integrations/fastapi.mdx`](diffhunk://#diff-53e2882747f27c6db0e429e457bccfab2b3405cf39b26e3e8c0d3e554788a6f4L137): Removed the unused `Mount` import from `starlette.routing` in the FastAPI integration example.

Remove unused import from FastAPI integration documentation

---

src/fastmcp/experimental/utilities/openapi/schemas.py
src/fastmcp/utilities/json_schema.py
src/fastmcp/utilities/openapi.py
tests/experimental/server/openapi/test_server.py
tests/experimental/server/test_openapi_performance.py
tests/utilities/test_json_schema.py

FastMCP's OpenAPI parser was experiencing severe performance bottlenecks when processing large schemas like GitHub's 10MB API specification, taking multiple minutes to parse. The primary culprits were expensive deep copy operations in `compress_schema()` and inefficient tree traversals in `_adjust_union_types()`.
This change delivers a 98.6% performance improvement, reducing parse time from multiple minutes to under 2 seconds through systematic optimization.
The main issue was that `compress_schema()` was calling `copy.deepcopy()` on the entire schema before processing, creating massive object copies for schemas that were already 10MB+ in size. Additionally, the function was making three separate passes through the schema tree for different cleanup operations, and `_adjust_union_types()` …

Optimize OpenAPI parser performance with single-pass schema processing

---

src/fastmcp/server/proxy.py
tests/server/proxy/test_proxy_client.py

fixes #1167
Instead of going through the context, the proxy elicitation handler here assumes that the original server did schema validation properly and bypasses it by going through the session directly.

Skip repeated type conversion and validation in proxy client elicitation handler

---

docs/servers/tools.mdx
src/fastmcp/utilities/types.py
tests/server/test_server_interactions.py
tests/utilities/test_types.py

This PR adds the ability to quickly provide argument descriptions by annotating the type with a string. The shorthand is only respected for Annotated variables with a single string argument.
```python
@mcp.tool
def my_tool(x: Annotated[int, "A number, should be > 100"]):
pass
```

Support creating tool argument descriptions from string annotations

---

src/fastmcp/experimental/server/openapi/components.py
tests/experimental/server/openapi/test_comprehensive.py

fix: experimental FastMCPOpenAPI server lost headers in request when __init__(client with headers)

---

docs/clients/prompts.mdx
docs/clients/resources.mdx
docs/clients/tools.mdx
docs/integrations/openapi.mdx
docs/servers/middleware.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
justfile
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/components.py
tests/server/openapi/test_basic_functionality.py
tests/server/test_server_interactions.py

Following the suggestion in #1258, this exposes FastMCP `tags` in the meta dict of all components, in order to facilitate client-side filtering. This is a huge step forward for client DX. Previously I believe the low-level SDK shadowed this assignment, but it appears to be available for server use now!
Closes #1258
Closes #824 
Closes #692 
Addresses #380

Expose FastMCP tags to clients via component `meta` dict

---

src/fastmcp/experimental/server/openapi/server.py
src/fastmcp/experimental/utilities/openapi/README.md
src/fastmcp/experimental/utilities/openapi/__init__.py
src/fastmcp/experimental/utilities/openapi/director.py
src/fastmcp/experimental/utilities/openapi/json_schema_converter.py
src/fastmcp/experimental/utilities/openapi/models.py
src/fastmcp/experimental/utilities/openapi/parser.py
src/fastmcp/experimental/utilities/openapi/schemas.py
src/fastmcp/server/openapi.py
src/fastmcp/utilities/openapi.py
tests/experimental/utilities/openapi/test_director.py
tests/experimental/utilities/openapi/test_nullable_fields.py

Changes:
- New JSON Schema converter - has version awareness for minor optimizations
- Removed old complex functions for handling nullable fields (not so old, introduced in #1279) and `_adjust_union_types`, among others
- fixed all deprecation warnings in experimental parser (mostly related to openapi_core and httpx misuse)

Improve OpenAPI-to-JSONSchema conversion utilities

---

docs/servers/middleware.mdx

Close #1284 by ensuring a version badge is displayed on the middleware docs. The equivalent version badge is already present in the Context docs:

Add 2.11 version badge for state management

---

docs/clients/prompts.mdx
docs/clients/resources.mdx
docs/clients/tools.mdx
docs/integrations/openapi.mdx
docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/server.mdx
docs/servers/tools.mdx
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/server/server.py
src/fastmcp/settings.py
src/fastmcp/tools/tool.py
src/fastmcp/utilities/components.py
tests/server/openapi/test_basic_functionality.py
tests/server/proxy/test_proxy_client.py
tests/server/proxy/test_proxy_server.py
tests/server/test_server_interactions.py

Follow-up to #1281
This PR introduces an optional `_fastmcp` namespace within the meta field of MCP components, providing a reserved space for FastMCP-specific metadata while maintaining backward compatibility.
Controls whether FastMCP adds its own metadata to component responses:
```python
mcp = FastMCP()  # or FastMCP(include_fastmcp_meta=True)
@mcp.tool(tags={"example", "utility"})
def my_tool():
pass
```
```python
mcp = FastMCP(include_fastmcp_meta=False)
@mcp.tool(tags={"example", "utility"})
def my_tool():
pass
```
The setting can be configured globally and inherited by servers:
```python
fastmcp.settings.include_fastmcp_meta = False
mcp = FastMCP()  # Will have include_fastmcp_meta=False
mcp_with_meta = FastMCP(include_fastmcp_meta=True)
```
Component metadata now uses a structured …

Add _fastmcp meta namespace

---

src/fastmcp/cli/cli.py
tests/cli/test_cli.py

Implement server argument passing after -- delimiter that was marked as TODO. This fixes the regression introduced in #1062.
Example: fastmcp run server.py -- --config config.json --debug

fix: server argument passing in CLI run command

---

docs/servers/prompts.mdx
docs/servers/resources.mdx
docs/servers/tools.mdx
src/fastmcp/prompts/prompt.py
src/fastmcp/resources/resource.py
src/fastmcp/resources/template.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool.py
tests/prompts/test_prompt.py
tests/resources/test_resource_template_meta.py
tests/resources/test_resources.py
tests/server/test_server.py
tests/tools/test_tool.py

This PR adds `meta` parameter support to all FastMCP component types (tools, resources, templates, and prompts), allowing developers to attach custom metadata to their MCP components.
```python
@mcp.tool()
def my_tool(): pass
@mcp.resource("resource://data")
def get_data(): pass
@mcp.prompt()
def my_prompt(): pass
```
```python
@mcp.tool(meta={"version": "1.0", "author": "test"})
def my_tool(): pass
@mcp.resource("resource://data", meta={"version": "2.0", "team": "data"})
def get_data(): pass
@mcp.resource("resource://{param}", meta={"version": "2.1", "template": "dynamic"}) 
def get_template(param: str): pass
@mcp.prompt(meta={"version": "1.5", "purpose": "analysis"})
def my_prompt(): pass
```
- Added `meta` parameter to all server decorator methods (`@mcp.tool`, `@mcp.resource`, …

Add meta parameter support to tools, resources, templates, and prompts decorators

---

src/fastmcp/experimental/utilities/openapi/json_schema_converter.py
src/fastmcp/experimental/utilities/openapi/parser.py
src/fastmcp/experimental/utilities/openapi/schemas.py
src/fastmcp/utilities/openapi.py

Replace inconsistent direct logging.getLogger(__name__) usage with FastMCP's standardized get_logger utility function across OpenAPI modules to ensure consistent logging behavior and namespace.
Changes:
- Replace logging.getLogger(__name__) with get_logger(__name__) in:
- src/fastmcp/utilities/openapi.py
- src/fastmcp/experimental/utilities/openapi/parser.py
- src/fastmcp/experimental/utilities/openapi/schemas.py
- src/fastmcp/experimental/utilities/openapi/json_schema_converter.py
- Remove direct logging imports where no longer needed
- Ensure all loggers use FastMCP namespace (FastMCP.<module>)
Benefits:
- Consistent logging configuration across all modules
- Proper integration with FastMCP's logging infrastructure
- Unified namespace for better log filtering and debugging
- Follows …

refactor: standardize logging usage across OpenAPI utilities

---

docs/patterns/cli.mdx
src/fastmcp/cli/cli.py
src/fastmcp/cli/install/claude_code.py
src/fastmcp/cli/install/claude_desktop.py
src/fastmcp/cli/install/cursor.py
src/fastmcp/cli/install/mcp_json.py
src/fastmcp/cli/install/shared.py
src/fastmcp/cli/run.py
tests/cli/test_cursor.py
tests/cli/test_run.py

Adds support for factory functions in `fastmcp run` to solve the issue where `fastmcp run` bypasses `if __name__ == "__main__"` blocks, preventing async setup code from running in environments like FastMCP Cloud.
Factory functions are auto-detected and can be sync or async. They take no arguments and must return a FastMCP server instance.
```python
async def create_server() -> FastMCP:
mcp = FastMCP("MyServer")
await initialize_async_resources()
return mcp
```
```bash
fastmcp run server.py:create_server
```

Support factory functions in fastmcp run

---

src/fastmcp/client/logging.py
tests/client/test_logs.py

The default_log_handler was incorrectly routing all server logs to logger.debug() regardless of their actual level. This prevented users from seeing INFO, WARNING, ERROR, and CRITICAL logs unless DEBUG was enabled globally.
This fix properly maps MCP log levels to appropriate Python logging levels so each message is logged at its intended severity.
Fixes #1394

Fix client-side logging bug #1394

---

.gitignore
src/fastmcp/server/http.py
src/fastmcp/settings.py
tests/client/test_openapi_experimental.py
tests/client/test_openapi_legacy.py
tests/client/test_streamable_http.py
tests/server/auth/test_static_token_verifier.py
tests/server/http/test_http_auth_middleware.py
tests/server/test_streamable_http_no_redirect.py

Adopts the strategy from the low-level SDK in PR 1115 to use Route instead of Mount in order to handle redirects properly and avoid issues with trailing slashes. Also restores default endpoints to have NO trailing slash, which is how most MCP clients are moving by convention.
Should help or resolve the following:
Closes #435 
Closes #1136 
Closes #585 
Closes #991

Improve redirect handling to address 307's

---

docs/servers/composition.mdx
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
src/fastmcp/utilities/components.py
tests/resources/test_resource_manager.py
tests/server/test_import_server.py
tests/server/test_mount.py
tests/tools/test_tool_manager.py
tests/utilities/test_components.py

Closes #1390 
This PR supersedes #1407 and #1411 by combining elements of both. Fundamentally we need to copy and modify additional elements of the component in order to prefix not only URIs but names as well. #1411 did this by using an actual `model_copy()` call, which is effective and readable but results in *two* copies (one to create the key, a second to move the name). #1407 added additional keywords to `with_key()`, which works functionally but ends up reimplementing `model_copy()` without clarity for future users on why `with_key` makes a full copy. This PR combines both by turning `with_key` into `model_copy` with an additional, special `key` argument.

Ensure resource + template names are properly prefixed when importing/mounting

---

src/fastmcp/experimental/utilities/openapi/schemas.py
tests/experimental/utilities/openapi/test_allof_requestbody.py

- Merge all properties from allOf sub-schemas when allOf appears at requestBody top level
- Properly combine required fields from all sub-schemas
- Add comprehensive tests for allOf merging scenarios
- Ensures all parameters from all allOf schemas are included in tool definitions
Fixes #1378

Fix OpenAPI allOf handling at requestBody top level (#1378)

---

src/fastmcp/experimental/server/openapi/server.py
src/fastmcp/experimental/utilities/openapi/__init__.py
src/fastmcp/experimental/utilities/openapi/formatters.py
src/fastmcp/experimental/utilities/openapi/models.py
src/fastmcp/experimental/utilities/openapi/parser.py
src/fastmcp/experimental/utilities/openapi/schemas.py
tests/experimental/openapi_parser/server/openapi/test_end_to_end_compatibility.py
tests/experimental/openapi_parser/utilities/openapi/test_models.py
tests/experimental/openapi_parser/utilities/openapi/test_parser.py
tests/experimental/openapi_parser/utilities/openapi/test_transitive_references.py

Closes #1449 and addresses #1372 by significantly reducing MCP payload sizes for large OpenAPI specifications.
Large OpenAPI specs like the Amazon Advertising API (567 schemas) were generating massive MCP payloads that exceeded Claude Desktop's context window. The main issues were:
1. Schema duplication between input and output definitions
2. Verbose descriptions including all response details, examples, and status codes
3. All schemas being included for both requests and responses even when not needed
This PR implements three key optimizations:
**1. Separated Input/Output Schema Dependencies**
- Replaced single `schema_definitions` field with separate `request_schemas` and `response_schemas`
- Each contains only the schemas actually needed for that direction
- Eliminates duplication …

Optimize OpenAPI payload size by 46%

---

docs/docs.json
docs/python-sdk/fastmcp-client-transports.mdx
docs/python-sdk/fastmcp-tools-tool.mdx
docs/python-sdk/fastmcp-tools-tool_transform.mdx
src/fastmcp/client/transports.py
src/fastmcp/tools/tool.py
src/fastmcp/tools/tool_transform.py
tests/deprecated/test_output_schema_false.py

PR #1443 inadvertently introduced a breaking change by removing support for `output_schema=False`. This PR restores backward compatibility while adding a deprecation warning to guide users to the preferred `output_schema=None` pattern.
After #1443, code using `output_schema=False` would fail with an assertion error:
```python
@mcp.tool(output_schema=False)
def my_tool() -> dict:
return {"status": "ok"}
```
This PR treats `output_schema=False` as a deprecated synonym for `output_schema=None`:
```python
@mcp.tool(output_schema=False)  # ⚠️ DeprecationWarning: Use output_schema=None
def my_tool() -> dict:
return {"status": "ok"}
@mcp.tool(output_schema=None)
def my_tool() -> dict:
return {"status": "ok"}
```
The deprecation warning appears in both direct tool creation and tool transformation …

Fix breaking change: restore output_schema=False compatibility

---

.github/workflows/run-static.yml
docs/python-sdk/fastmcp-cli-run.mdx
docs/python-sdk/fastmcp-server-auth-auth.mdx
docs/python-sdk/fastmcp-server-context.mdx
docs/python-sdk/fastmcp-utilities-components.mdx
src/fastmcp/cli/run.py
src/fastmcp/experimental/server/openapi/routing.py
src/fastmcp/experimental/server/openapi/server.py
src/fastmcp/server/auth/auth.py
src/fastmcp/server/context.py
src/fastmcp/utilities/components.py
src/fastmcp/utilities/json_schema_type.py

This is a hygiene PR to remove some unnecessary asserts. In the (rare) case these were actually hit, they raise without errors causing confusion -- the original motivation for most was for typing purposes.

Remove unnecessary asserts

---

docs/servers/prompts.mdx

This PR fixes a small documentation issue I came across whilst reading the docs. When using this code directly from the example, one would get  the following type checker error:
```
error: Expected class but received "(content: ContentBlock | str, role: Role | None = None, **kwargs: Any) -> PromptMessage" (reportGeneralTypeIssues)
```
The return type annotation should be `PromptMessage` here I believe. Thanks for the work on the package!

docs: Fix type annotation in return value documentation

---

.github/workflows/run-static.yml
.github/workflows/update-sdk-docs.yml

Moves SDK documentation generation from PR checks to a post-merge workflow to prevent blocking contributors with confusing failures.
- Extract SDK doc check from `run-static.yml` that was blocking PRs
- New `update-sdk-docs.yml` runs on merges to main and auto-commits updated docs
- Eliminates race condition failures when multiple PRs are merged
The SDK docs will now stay current automatically without interrupting the contributor workflow.

Move SDK docs generation to post-merge workflow

---

.github/workflows/marvin.yml

Adds support for triggering the Marvin workflow when `/marvin` appears in pull request bodies, not just in comments.
This allows Marvin to respond immediately when PRs are opened or edited with the trigger phrase.

feat: trigger Marvin workflow on PR body content

---

.github/workflows/marvin-label-triage.yml

The triage bot was failing on PRs from forks because the `pull_request` event doesn't have access to repository secrets when triggered by forks. This PR switches to `pull_request_target` which runs in the base repository context with access to secrets.
- Switch from `pull_request` to `pull_request_target` event  
- Explicitly checkout the base repository (not fork code) for security
- Bot can now triage and label PRs from forks automatically
The workflow remains secure because we never execute fork code - we only checkout our base repository and use the GitHub API to read PR metadata and apply labels.

fix: enable triage bot for fork PRs using pull_request_target

---

docs/servers/auth/oauth-proxy.mdx
src/fastmcp/server/auth/__init__.py

I fixed import path in docs, but this time I've added import to auth `__init__.py`, so next time it won't be required to update docs, if something will be updated again ;)

Added import of AuthProxy to auth __init__

---

.github/workflows/marvin-dedupe-issues.yml
.github/workflows/marvin-label-triage.yml

This PR switches our two Marvin "restricted" workflows to use Haiku (as an experiment) and a separate API key for cost tracking.

Experiment with haiku for limited workflows

---

src/fastmcp/server/auth/oauth_proxy.py
tests/server/auth/test_oauth_proxy.py

Closes #1618
The OAuthProxy is inadvertently sending the "true" client secret back to the MCP client, which is obviously bad. I think these assignments were part of testing visibility that should have been deleted, though I was under the impression that the SDK did not use this object (in fact, it doesn't depend on it being returned from the function that was modifying it, but it does send the modified object back to the client, hence the bug)

Remove client info modifications

---

docs/deployment/server-configuration.mdx
docs/patterns/cli.mdx
src/fastmcp/cli/claude.py
src/fastmcp/cli/cli.py
src/fastmcp/cli/install/claude_code.py
src/fastmcp/cli/install/claude_desktop.py
src/fastmcp/cli/install/cursor.py
src/fastmcp/cli/install/mcp_json.py
src/fastmcp/cli/run.py
src/fastmcp/utilities/fastmcp_config/v1/fastmcp_config.py
src/fastmcp/utilities/fastmcp_config/v1/schema.json
tests/cli/test_cli.py
tests/cli/test_config.py
tests/cli/test_cursor.py
tests/cli/test_project_prepare.py
tests/cli/test_run_config.py
tests/cli/test_run_with_uv.py
tests/utilities/test_cli.py

This PR refines the fastmcp.json environment configuration story, particularly around editable packages and project-based deployments. These changes emerged from real-world usage patterns where users need to prepare environments in CI/CD pipelines and work with multiple editable packages simultaneously.
The `environment.editable` field in fastmcp.json now accepts a list of paths instead of a single string:
```json
{
"environment": {
"dependencies": ["pandas", "numpy"],
"editable": [".", "../shared-lib", "/path/to/dev-package"]
}
}
```
This enables development workflows where multiple packages need to be installed in editable mode, a common pattern when working with monorepos or shared libraries.
Previously, using `--project` would completely ignore any additional dependencies from the …

Improve fastmcp.json environment configuration and project-based deployments

---

docs/servers/auth/oauth-proxy.mdx
src/fastmcp/server/auth/oauth_proxy.py
src/fastmcp/server/auth/redirect_validation.py
tests/server/auth/test_oauth_proxy_redirect_validation.py
tests/server/auth/test_redirect_validation.py

The current localhost-only default breaks MCP's Dynamic Client Registration pattern where clients register with unpredictable redirect URIs. This particularly affects hosted clients like Claude.ai (#1628).
Note this relaxes the stance taken in #1582 which fails for hosted clients
- Default (`None`): Allow all URIs for DCR compatibility  
- Empty list: Block all URIs (more intuitive than allowing all)
- Custom patterns: Only allow matches
Users can still restrict redirect URIs if they know their clients, but most MCP servers need the flexibility of DCR.
Closes #1564, closes #1628

Fix OAuth redirect URI validation for DCR compatibility

---

src/fastmcp/server/auth/providers/azure.py
src/fastmcp/server/auth/providers/github.py
src/fastmcp/server/auth/providers/google.py
src/fastmcp/server/auth/providers/workos.py

All OAuthProxy subclasses (Google, GitHub, Azure, WorkOS) now accept the `allowed_client_redirect_uris` parameter, completing the redirect URI restriction feature.
Closes #1658

Add allowed_client_redirect_uris to OAuth provider subclasses

---

src/fastmcp/cli/claude.py
src/fastmcp/cli/cli.py
src/fastmcp/cli/install/claude_code.py
src/fastmcp/cli/install/claude_desktop.py
src/fastmcp/cli/install/cursor.py
src/fastmcp/cli/install/mcp_json.py
src/fastmcp/cli/install/shared.py
src/fastmcp/cli/run.py
src/fastmcp/utilities/cli.py
src/fastmcp/utilities/fastmcp_config/v1/fastmcp_config.py
tests/cli/test_config.py
tests/cli/test_fastmcp_config_integration.py
tests/cli/test_run_config.py
tests/cli/test_run_with_uv.py
tests/utilities/test_cli.py

This PR consolidates duplicated config parsing logic across CLI commands and eliminates a dangerous footgun where forgetting to pass `--skip-env` would cause infinite subprocess loops.
Previously, multiple CLI commands (`run`, `inspect`, `dev`) had:
- Duplicated config parsing logic
- Manual requirement to pass `--skip-env` flag when spawning nested environments
- Risk of infinite loops if `--skip-env` was forgotten
Created `load_and_merge_config()` in `utilities/cli.py` that:
- Handles all config file loading and parsing
- Merges CLI overrides with config values
- Returns an immutable config (no mutation of original)
- Added `FASTMCP_UV_SPAWNED` environment marker
- Commands automatically detect if they're already in a uv subprocess
- Eliminates need for manual `--skip-env` flag (though …

Consolidate CLI config parsing and prevent infinite loops

---

src/fastmcp/client/auth/oauth.py
tests/client/auth/test_oauth_token_expiry.py

OAuth tokens loaded from storage were never proactively refreshed, only refreshing after hitting a 401 error. This happened because:
1. **Relative time becomes meaningless**: MCP's `OAuthToken` stores `expires_in` (seconds until expiry), not an absolute timestamp. When saved and reloaded later, a token with `expires_in=3600` still reports 3600 seconds remaining, even if hours have passed.
2. **Missing expiry initialization**: The `_initialize()` method loads tokens but never calls `update_token_expiry()`, leaving `token_expiry_time` as `None`. The SDK's `is_token_valid()` treats `None` as "never expires".
3. **No validation on load**: Tokens were returned from storage without checking if they had expired.
Store an absolute `expires_at` timestamp alongside tokens, then recalculate …

Fix OAuth token expiry handling

---

docs/deployment/server-configuration.mdx
src/fastmcp/utilities/mcp_server_config/__init__.py
src/fastmcp/utilities/mcp_server_config/v1/environments/base.py
src/fastmcp/utilities/mcp_server_config/v1/environments/uv.py
src/fastmcp/utilities/mcp_server_config/v1/mcp_server_config.py
src/fastmcp/utilities/mcp_server_config/v1/sources/base.py
src/fastmcp/utilities/mcp_server_config/v1/sources/filesystem.py
tests/cli/test_config.py
tests/cli/test_mcp_server_config_schema.py

Following the same pattern as Source classes, adds a mandatory `type` field to the Environment base class.
This prepares for future environment types (NodeEnvironment, DockerEnvironment, etc.) that will use discriminated unions for automatic type selection.
Changes:
- Add `type` field to Environment base class  
- Use `Literal['uv']` for UVEnvironment type
- Simplify validators to let Pydantic handle type validation
- Update test to account for type field having a default value

Add type field to Environment base class

---

docs/servers/auth/oauth-proxy.mdx
docs/servers/auth/remote-oauth.mdx
examples/auth/azure_oauth/server.py
examples/auth/github_oauth/server.py
examples/auth/google_oauth/server.py
examples/auth/workos_oauth/server.py
src/fastmcp/server/auth/oauth_proxy.py
src/fastmcp/server/auth/providers/azure.py
src/fastmcp/server/auth/providers/github.py
src/fastmcp/server/auth/providers/google.py
src/fastmcp/server/auth/providers/workos.py

This PR adds the `resource_server_url` parameter to all OAuth proxy providers, ensuring that the OAuth protected resource metadata correctly identifies the actual MCP endpoint path.
- Added `resource_server_url` parameter to GitHub, Azure, and WorkOS OAuth providers (matching the Google provider implementation)
- Updated documentation to clarify that `resource_server_url` should point to the MCP endpoint (e.g., `/mcp` for HTTP servers)
The OAuth protected resource metadata needs to identify the actual MCP endpoint, not just the base server URL. This ensures proper RFC 8707 compliance and allows clients to correctly identify the protected resource.
Resolves #1348

Add resource_server_url parameter to OAuth proxy providers

---

examples/sampling_fallback.py
pyproject.toml
src/fastmcp/experimental/sampling/handlers/__init__.py
src/fastmcp/experimental/sampling/handlers/openai.py
uv.lock

Closes #1696 by moving openai to an optional dependency, with an informative message.

Make openai depedency optional

---

.github/workflows/run-tests.yml

These tests are occasionally failing because they take longer than 3 seconds. Failures are only expected due to 429s from the GitHub server due to rate limiting(though its possible a retry is exacerbating the issue)

Run integration tests with a longer timeout

---

docs/servers/auth/oauth-proxy.mdx
src/fastmcp/server/auth/oauth_proxy.py
tests/server/auth/test_oauth_proxy.py

This PR improves upon #1752 by providing a cleaner, more flexible approach for forwarding provider-specific parameters to upstream OAuth providers.
PR #1752 introduced tight coupling between the OAuth proxy and token verifier by directly accessing the verifier's `audience` attribute. This approach was inflexible and created unnecessary dependencies between components.
This implementation provides explicit configuration options for parameter forwarding:
- **`extra_authorize_params`**: Forward custom parameters to the authorization endpoint (e.g., Auth0's `audience`)
- **`extra_token_params`**: Forward custom parameters to the token endpoint
- **RFC 8707 support**: Automatically forward the standard `resource` parameter when provided by clients
```python
auth = OAuthProxy( …
```

feat: Add flexible parameter forwarding to OAuth proxy

---

src/fastmcp/server/http.py

Move the Starlette context middleware to the front to facilitate subsequent middleware to obtain request information
related issue: https://github.com/jlowin/fastmcp/issues/1811
Closes 1811

feat: Move the Starlette context middleware to the front

---

src/fastmcp/server/middleware/logging.py
tests/server/middleware/test_logging.py

Consolidate the Logging and Structured Logging Middleware to share a common implementation and differ only in how the actual message is formatted.
Continue to maintain both classes to make this hopefully not a breaking change.
Also add payload size and payload token estimation (length // 4)
Fixes #1801

Refactor Logging and Structured Logging Middleware

---

src/fastmcp/client/auth/oauth.py

Fixes #1798 
Some OAuth providers return HTTP 200 with HTML login pages instead of redirects during the pre-flight check. This is valid behavior - OAuth specifications don't mandate redirect responses for authorization endpoints, and providers may choose to serve interactive HTML forms directly.
The pre-flight check's primary purpose is to catch invalid client IDs (400 errors) early before opening the browser. Accepting 200 responses alongside redirect codes (302, 303, 307, 308) allows these providers to work while preserving the invalid client detection.
This restores compatibility with SSE-based OAuth flows and other providers that serve login pages directly.

Fix OAuth pre-flight check to accept HTTP 200 responses

---

src/fastmcp/experimental/utilities/openapi/schemas.py
tests/experimental/openapi_parser/server/openapi/test_openapi_features.py

Closes #1876
Problem: When generating tools from OpenAPI with the experimental parser, parameter descriptions (e.g., query params) were not preserved in tool inputSchema, unlike the stable path.
Solution: Thread the parameter’s description into schema resolution and set it on non-ref schemas when missing, in both collision and non-collision branches. This aligns experimental behavior with the stable combiner.
Before
```python
param_schema = _replace_ref_with_defs(param.schema_)
param_schema = param.schema_
```
After
```python
param_schema = _replace_ref_with_defs(param.schema_, param.description)
param_schema = param.schema_.copy()
if param.description and not param_schema.get("description"):
param_schema["description"] = param.description
```
Refs: #1876
Note (as requested):
- Used AI …

Fix: Preserve OpenAPI parameter descriptions in experimental parser

---

docs/servers/auth/oauth-proxy.mdx
src/fastmcp/client/auth/oauth.py
src/fastmcp/server/auth/oauth_proxy.py
src/fastmcp/server/auth/oidc_proxy.py
src/fastmcp/server/auth/providers/auth0.py
src/fastmcp/server/auth/providers/azure.py
src/fastmcp/server/auth/providers/github.py
src/fastmcp/server/auth/providers/google.py
src/fastmcp/server/auth/providers/workos.py
src/fastmcp/utilities/storage.py
tests/client/auth/test_oauth_token_expiry.py
tests/server/auth/test_oauth_proxy.py
tests/server/auth/test_oauth_proxy_storage.py
tests/utilities/test_storage.py

Fixes #1762 - OAuth proxy now persists client registrations across server restarts.
- Created KVStorage protocol and JSONFileStorage implementation using pydantic_core
- OAuth proxy now uses storage interface (defaults to file-based)
- Removed in-memory client caching - storage is the single source of truth
- Added InMemoryStorage for testing/special cases
- Client data stored as structured JSON with metadata
Closes #1762 and builds on work first introduced in code in #1806
This also adds a supported Storage protocol and uses it to improve the client-side token storage

Add persistent storage for OAuth client registrations

---

src/fastmcp/server/openapi.py

The OpenAPI server was reporting the total number of routes without accounting for excluded routes. When routes are excluded via `MCPType.EXCLUDE`, the log message would still report the original total, making it confusing to understand how many routes were actually processed.
This PR adds a counter for excluded routes and subtracts it from the total when logging, providing accurate feedback about the number of routes that were actually created as MCP components.
Before: `Created FastMCP OpenAPI server with 5 routes` (even though 2 were excluded)
After: `Created FastMCP OpenAPI server with 3 routes` (correctly shows only processed routes)
Fixes #1899
<details>
<summary>Reproduction Script</summary>
```python
"""
Reproduction for issue #1899: Wrong count of routes in log message
The issue …
```

Fix route count logging in OpenAPI server

---

docs/integrations/chatgpt.mdx

ChatGPT now supports MCP servers in regular Chat conversations through Developer Mode. This PR updates the documentation to reflect these new capabilities while maintaining the existing Deep Research mode documentation.

Update ChatGPT docs for Chat mode with Developer Mode

---

src/fastmcp/server/auth/oauth_proxy.py
tests/server/auth/test_oauth_proxy.py

This PR refines the OAuth 2.1 error handling approach from #1923 by using a cleaner `TokenHandler` subclass instead of wrapping and parsing responses.
Per OAuth 2.1 Section 5.3 and MCP spec requirements, invalid clients must receive HTTP 401.
**Note:** This replaces the implementation from #1923. The original approach was completely valid and we appreciate the contribution! This refactor just makes the code a bit more maintainable by working at the model layer rather than parsing serialized responses. I think the only operational difference here is maintaining the SDK's use of CORS middleware - I am not sure to what degree this has impact.

Refactor OAuth 2.1 error handling with TokenHandler subclass

---

.github/workflows/run-tests.yml
tests/client/test_sse.py

Since merging #1949 there have been elevated rates of test failures when testing timeouts. In particular, a small number of tests with a 0.01 second sensitivity. These are stochastic and usually solved by rerunning the test suite. I suspect that setting up the websocket (which wasn't happening previously) is sufficient to push the test beyond the 0.01 threshold. Therefore this PR expands it to 0.03 seconds.

Expand timeouts

---

pyproject.toml
src/fastmcp/cli/install/claude_code.py
src/fastmcp/cli/install/claude_desktop.py
src/fastmcp/cli/install/cursor.py
src/fastmcp/cli/install/gemini_cli.py
src/fastmcp/cli/install/mcp_json.py
src/fastmcp/client/oauth_callback.py
src/fastmcp/client/transports.py
src/fastmcp/server/server.py
src/fastmcp/utilities/mcp_server_config/v1/environments/uv.py
src/fastmcp/utilities/mcp_server_config/v1/mcp_server_config.py
src/fastmcp/utilities/tests.py
tests/cli/test_config.py
tests/cli/test_mcp_server_config_integration.py
tests/client/test_sse.py
tests/client/test_streamable_http.py
tests/client/transports/test_uv_transport.py
tests/server/auth/test_oauth_proxy.py
tests/utilities/test_cli.py
uv.lock

Relative paths like `--with-editable .` were not being expanded to absolute paths in generated configs. 
Changed `UVEnvironment` to accept `Path` objects for `requirements`, `project`, and `editable` parameters and handle resolution internally. Updated all install commands and `UvStdioTransport` to use `Path` objects.

Fix path resolution in install commands

---

src/fastmcp/server/auth/auth.py
src/fastmcp/server/auth/oauth_proxy.py
src/fastmcp/server/auth/providers/descope.py
src/fastmcp/server/auth/providers/scalekit.py
src/fastmcp/server/auth/providers/workos.py
src/fastmcp/server/http.py

Fixes #1903
After d36ea42b, the SSE endpoint (`/sse`) started accepting POST requests and returning 200 OK instead of rejecting them with 405 Method Not Allowed. This expected MCP semantics and caused clients (like Claude Desktop) to stop their search and not communicate with the "correct" SSE endpoint via a GET request.
The refactoring centralized MCP endpoint route creation in `AuthProvider.get_routes()`, but didn't specify HTTP methods, causing routes to accept all methods by default.
Separated responsibilities clearly:
- **Auth providers** (`get_routes()`) return only their own routes (OAuth endpoints, metadata)
- **Transport layer** (`http.py`) creates the protected MCP endpoint routes with correct methods:
- SSE: `methods=["GET"]` only
- Streamable HTTP: no method restriction (as …

Fix SSE endpoint accepting POST requests instead of returning 405

---

.github/workflows/marvin-dedupe-issues.yml
.github/workflows/marvin-label-triage.yml

Fixes the automation workflows (triage and dedupe) to work with claude-code-action@v1.
**Changes:**
- Replace `prompt_file` with `prompt` input (using GitHub output variables)
- Add `bot_name: "Marvin Context Protocol"` for proper attribution
- Keep `github_token` (matches working marvin.yml configuration)
- Keep `id-token: write` permission
The `prompt_file` input doesn't exist in v1, causing warnings. The new approach uses GitHub Actions output variables to pass the prompt text directly.

Fix prompt_file input and bot attribution

---

docs/servers/resources.mdx
src/fastmcp/resources/template.py
tests/resources/test_resource_template.py
tests/server/test_server_interactions.py

FastMCP already supported RFC 6570 simple expansion (`{var}`) and wildcard parameters (`{var*}`). This adds form-style query parameters (`{?param1,param2}`) to complete our RFC 6570 implementation.
Query parameters provide a clean way to pass optional configuration to resources. Parameters declared with `{?...}` syntax can be overridden via query string, while optional parameters omitted from the template always use their defaults.
```python
@mcp.resource("data://{id}{?format,limit}")
def get_data(id: str, format: str = "json", limit: int = 10) -> str:
return f"id={id}, format={format}, limit={limit}"
```
Type coercion happens automatically based on function type hints (int, float, bool, str).

Add RFC 6570 query parameter support to resource templates

---

src/fastmcp/utilities/cli.py

Fix: Align CLI banner box edges by removing emoji variation selectors
you can also see this on all FastMCP cloud server logs
Problem
- The right border of the startup banner panel appeared jagged/misaligned.
- Root cause: two emojis in the info table included Unicode variation selectors (VS16):
- U+1F5A5 U+FE0F (🖥️) on "Server name"
- U+1F3CE U+FE0F (🏎️) on "FastMCP version"
- Many terminals and width calculators treat emoji with VS16 as double‑width (2 columns). Rich's table width calculations then disagree with the terminal's display width, shifting content to the right and causing the panel's right edge to be off.
Change
- Replace the two emojis with their base forms (no variation selector):
- 🖥️ → 🖥
- 🏎️ → 🏎
- No other layout or sizing changes. The table/panel centering and width …

cli: fix banner width by removing emoji variation selectors

---

pyproject.toml
tests/integration_tests/test_github_mcp_remote.py
uv.lock

Add pytest-retry and mark GitHub Integration tests as flaky, allowing 2 retries with a 1s delay

Mark GitHub Integration tests as flaky

---

examples/mount_example.py
examples/serializer.py
src/fastmcp/prompts/prompt_manager.py
src/fastmcp/resources/resource_manager.py
src/fastmcp/server/context.py
src/fastmcp/server/server.py
src/fastmcp/tools/tool_manager.py
tests/server/http/test_custom_routes.py
tests/server/openapi/test_openapi_path_parameters.py
tests/server/proxy/test_proxy_server.py
tests/server/test_file_server.py
tests/server/test_server.py
tests/server/test_tool_annotations.py
tests/server/test_tool_transformation.py

This pull request refactors and standardizes the internal API and method naming conventions for MCP handlers. Specifically, it takes what used to be two methods and a JIT-generated handler and refactors them into three handlers:
`_list_tools_mcp`: previously `_mcp_list_tools`, this method is the registered handler with the low-level MCP server and returns the handler result in MCP-native format
`_list_tools_middleware`: previously `_list_tools`, this method applies MCP middleware
`_list_tools`: previously generated dynamically in `_list_tools_middleware`, this is the core handler that is responsible for listing tools
This makes it more clear where responsibility lies and avoids dynamically generating new functions unnecessarily, which made debugging more difficult.
In addition, an …

Internal refactor of MCP handlers
